/* Generated by AN DISI Unibo */ 
package it.unibo.ctxRobot;
import it.unibo.qactors.ActorContext;
import java.io.InputStream;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;
public class MainCtxRobot extends ActorContext{
//private IBasicEnvAwt env; 
 
	public MainCtxRobot(String name, IOutputEnvView outEnvView,
			InputStream sysKbStream, InputStream sysRulesStream) throws Exception {
		super(name, outEnvView, sysKbStream, sysRulesStream);
		this.outEnvView = outEnvView;
		env = outEnvView.getEnv();
 	}
	@Override
	public void configure() {
		try {
		SituatedSysKb.init();	//Init the schedulers
		println("Starting the actors .... ");	
new it.unibo.robot.Robot("robot", this, outEnvView);
		
 		} catch (Exception e) {
 		  e.printStackTrace();
		} 		
	}
 	
/*
* ----------------------------------------------
* MAIN
* ----------------------------------------------
*/
 	
public static void main(String[] args) throws Exception{
	IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
 		InputStream sysKbStream    = //MainCtxRobot.class.getResourceAsStream("scout.pl");
 			new java.io.FileInputStream("./srcMore/it/unibo/ctxRobot/scout.pl");
	InputStream sysRulesStream = MainCtxRobot.class.getResourceAsStream("sysRules.pl");
	new MainCtxRobot("ctxRobot", outEnvView, sysKbStream, sysRulesStream ).configure();
 	} 	
}
