/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.planner;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.ActorContext;

public class Planner extends AbstractPlanner { 
	public Planner(String actorId, ActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
	
	
	public String cleanPlan(String plan)
	{
		String clean = "";
		
		println(plan);
		plan = plan.replace("[", "");
		plan = plan.replace("]", "");
		plan = plan.replace("'", "");
		plan = plan.replace(",", "\n");
		
		println(plan);
		
		
		return clean;
	}
	
	
}
