/* Generated by AN DISI Unibo */ 
package it.unibo.robot;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.ActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.planned.QActorPlanned;
import it.unibo.qactors.action.ActionDummy;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.iot.configurator.Configurator;
import it.unibo.iot.executors.baseRobot.IBaseRobot; 
import it.unibo.iot.models.sensorData.distance.IDistanceSensorData;
import it.unibo.iot.models.sensorData.line.ILineSensorData;
import it.unibo.iot.models.sensorData.magnetometer.IMagnetometerSensorData;
import it.unibo.iot.sensors.ISensor; 
import it.unibo.iot.sensors.ISensorObserver;
import it.unibo.iot.sensors.distanceSensor.DistanceSensor;
import it.unibo.iot.sensors.lineSensor.LineSensor;
import it.unibo.iot.sensors.magnetometerSensor.MagnetometerSensor;

public class AbstractRobot extends it.unibo.qactor.robot.RobotActor { 
protected AsynchActionResult aar = null;
protected boolean actionResult = true;
protected alice.tuprolog.SolveInfo sol;

		protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
			return outEnvView;
		}


	public AbstractRobot(String actorId, ActorContext myCtx, IOutputEnvView outEnvView ,it.unibo.iot.executors.baseRobot.IBaseRobot baserobot)  throws Exception{
		super(actorId, myCtx, "./srcMore/it/unibo/robot/plans.txt", 
		"./srcMore/it/unibo/robot/WorldTheory.pl",
		setTheEnv( outEnvView ) ,baserobot , "init");		
 	}
	@Override
	protected void doJob() throws Exception {
 		initSensorSystem();
		boolean res = init();
		//println(getName() + " doJob " + res );
	} 
	/* 
	* ------------------------------------------------------------
	* PLANS
	* ------------------------------------------------------------
	*/
    public boolean init() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "init";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		{ String parg = "consult( \"robotTheory.pl\" )";
    		  aar = solveGoal( parg , 210000000, "","" , "" );
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "init";
    			if( ! aar.getGoon() ) break;
    		} 			
    		if( aar.getResult().equals("failure")){
    		if( ! switchToPlan("consultPrologFailure").getGoon() ) break;
    		}else if( ! aar.getGoon() ) break;
    		}
    		{ String parg = "consult( \"navRobotTheory.pl\" )";
    		  aar = solveGoal( parg , 210000000, "","" , "" );
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "init";
    			if( ! aar.getGoon() ) break;
    		} 			
    		if( aar.getResult().equals("failure")){
    		if( ! switchToPlan("consultPrologFailure").getGoon() ) break;
    		}else if( ! aar.getGoon() ) break;
    		}
    		{ String parg = "consult( \"expRobotTheory.pl\" )";
    		  aar = solveGoal( parg , 210000000, "","" , "" );
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "init";
    			if( ! aar.getGoon() ) break;
    		} 			
    		if( aar.getResult().equals("failure")){
    		if( ! switchToPlan("consultPrologFailure").getGoon() ) break;
    		}else if( ! aar.getGoon() ) break;
    		}
    		{ String parg = "consult( \"talkTheory.pl\" )";
    		  aar = solveGoal( parg , 210000000, "","" , "" );
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "init";
    			if( ! aar.getGoon() ) break;
    		} 			
    		if( aar.getResult().equals("failure")){
    		if( ! switchToPlan("consultPrologFailure").getGoon() ) break;
    		}else if( ! aar.getGoon() ) break;
    		}
    		temporaryStr = " \"++++++++++++++++++ robot(starts) ++++++++++++++++++\" ";
    		println( temporaryStr );  
    		if( ! switchToPlan("waitConsoleCommand").getGoon() ) break;
    break;
    }//while
    return returnValue;
    }catch(Exception e){
    println( getName() + " ERROR " + e.getMessage() );
    throw e;
    }
    }
    public boolean waitConsoleCommand() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "waitConsoleCommand";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		temporaryStr = " \"++++++++++++++++++ WAIT CONSOLE COMMAND ++++++++++++++++++\" ";
    		println( temporaryStr );  
    		//ReceiveMsg
    		 		 aar = receiveAMsg(600000000, "" , "" ); 	//could block
    				if( aar.getInterrupted() ){
    					curPlanInExec   = "playTheGame";
    					if( ! aar.getGoon() ) break;
    				} 			
    				if( ! aar.getGoon() ){
    					System.out.println("			WARNING: receiveMsg in " + getName() + " TOUT " + aar.getTimeRemained() + "/" +  600000000);
    					addRule("tout(receive,"+getName()+")");
    				} 		 
    				//println(getName() + " received " + aar.getResult() );
    		printCurrentMessage(false);
    		memoCurrentMessage( false );
    		//onMsg
    		if( currentMessage.msgId().equals("explore") ){
    			String parg = "";
    			parg = updateVars(null, Term.createTerm("explore"), Term.createTerm("explore"), 
    				    		  					Term.createTerm(currentMessage.msgContent()), parg);
    				if( parg != null ){
    					 if( ! switchToPlan("exploration").getGoon() ) break; 
    				}//else println("guard  fails");  //parg is null when there is no guard (onEvent)
    		}//onMsg
    		if( currentMessage.msgId().equals("explore") ){
    			String parg = "";
    			parg = updateVars(null, Term.createTerm("explore"), Term.createTerm("explore(START,BOUNDS)"), 
    				    		  					Term.createTerm(currentMessage.msgContent()), parg);
    				if( parg != null ){
    					 if( ! switchToPlan("explorationDebug").getGoon() ) break; 
    				}//else println("guard  fails");  //parg is null when there is no guard (onEvent)
    		}//onMsg
    		if( currentMessage.msgId().equals("navigate") ){
    			String parg = "";
    			parg = updateVars(null, Term.createTerm("navigate(PLAN,POS)"), Term.createTerm("navigate(PLAN,POS)"), 
    				    		  					Term.createTerm(currentMessage.msgContent()), parg);
    				if( parg != null ){
    					 if( ! switchToPlan("navigation").getGoon() ) break; 
    				}//else println("guard  fails");  //parg is null when there is no guard (onEvent)
    		}if( repeatPlan(0).getGoon() ) continue;
    break;
    }//while
    return returnValue;
    }catch(Exception e){
    println( getName() + " ERROR " + e.getMessage() );
    throw e;
    }
    }
    public boolean exploration() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "exploration";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		temporaryStr = " \"\" ";
    		println( temporaryStr );  
    break;
    }//while
    return returnValue;
    }catch(Exception e){
    println( getName() + " ERROR " + e.getMessage() );
    throw e;
    }
    }
    public boolean explorationDebug() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "explorationDebug";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		temporaryStr = " \"\" ";
    		println( temporaryStr );  
    break;
    }//while
    return returnValue;
    }catch(Exception e){
    println( getName() + " ERROR " + e.getMessage() );
    throw e;
    }
    }
    public boolean navigation() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "navigation";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		if( (guardVars = evalTheGuard( " !?planFilename(FILENAME)" )) != null ){
    		{ String parg = "loadThePlan(FILENAME)";
    		parg = substituteVars(guardVars,parg);
    		  aar = solveGoal( parg , 300000000, "","" , "" );
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "navigation";
    			if( ! aar.getGoon() ) break;
    		} 			
    		if( aar.getResult().equals("failure")){
    		if( ! aar.getGoon() ) break;
    		}else if( ! aar.getGoon() ) break;
    		}
    		}
    		temporaryStr = " \"++++++++++++++++++ Plan Loaded ++++++++++++++++++\" ";
    		println( temporaryStr );  
    		temporaryStr = " \" \" ";
    		println( temporaryStr );  
    		temporaryStr = " \" \" ";
    		println( temporaryStr );  
    		if( (guardVars = evalTheGuard( " !?planName(PLANNAME)" )) != null ){
    		{ String parg = "showPlan(path)";
    		parg = substituteVars(guardVars,parg);
    		  aar = solveGoal( parg , 1000, "","" , "" );
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "navigation";
    			if( ! aar.getGoon() ) break;
    		} 			
    		if( aar.getResult().equals("failure")){
    		if( ! aar.getGoon() ) break;
    		}else if( ! aar.getGoon() ) break;
    		}
    		}
    		temporaryStr = " \" \" ";
    		println( temporaryStr );  
    		temporaryStr = " \" \" ";
    		println( temporaryStr );  
    		temporaryStr = " \"++++++++++++++++++ ++++++++++++++++++ ++++++++++++++++++\" ";
    		println( temporaryStr );  
    		{ String parg = "runResumablePlan(path)";
    		  aar = solveGoal( parg , 2100000000, "","" , "" );
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "navigation";
    			if( ! aar.getGoon() ) break;
    		} 			
    		if( aar.getResult().equals("failure")){
    		if( ! aar.getGoon() ) break;
    		}else if( ! aar.getGoon() ) break;
    		}
    break;
    }//while
    return returnValue;
    }catch(Exception e){
    println( getName() + " ERROR " + e.getMessage() );
    throw e;
    }
    }
    public boolean abort() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "abort";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		temporaryStr = " \"Current command aborted\" ";
    		println( temporaryStr );  
    		if( ! switchToPlan("waitConsoleCommand").getGoon() ) break;
    break;
    }//while
    return returnValue;
    }catch(Exception e){
    println( getName() + " ERROR " + e.getMessage() );
    throw e;
    }
    }
    public boolean waitAndEvaluate() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "waitAndEvaluate";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		temporaryStr = " \"maybe there is an unexpected static obstacle\" ";
    		println( temporaryStr );  
    		//delay
    		aar = delayReactive(60000,"" , "");
    		if( aar.getInterrupted() ) curPlanInExec   = "waitAndEvaluate";
    		if( ! aar.getGoon() ) break;
    		temporaryStr = " \"are you there obstalce ??\" ";
    		println( temporaryStr );  
    		//senseEvent
    		timeoutval = 5000;
    		aar = senseEvents( timeoutval,"obstacle","notifyUnexpectedObstacle",
    		"" , "",ActionExecMode.synch );
    		if( ! aar.getGoon() || aar.getTimeRemained() <= 0 ){
    			println("			WARNING: sense timeout");
    			addRule("tout(senseevent,"+getName()+")");
    			//break;
    		}
    		returnValue = continueWork;  
    break;
    }//while
    return returnValue;
    }catch(Exception e){
    println( getName() + " ERROR " + e.getMessage() );
    throw e;
    }
    }
    public boolean notifyUnexpectedObstacle() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "notifyUnexpectedObstacle";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		temporaryStr = " \"I found an unexpected static obstacle\" ";
    		println( temporaryStr );  
    		{ String parg = "getCurrentPosition(CURRENT)";
    		  aar = solveGoal( parg , 2100000000, "","" , "" );
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "notifyUnexpectedObstacle";
    			if( ! aar.getGoon() ) break;
    		} 			
    		if( aar.getResult().equals("failure")){
    		if( ! switchToPlan("navigationFailure").getGoon() ) break;
    		}else if( ! aar.getGoon() ) break;
    		}
    		{ String parg = "getObstaclePosition(OBJECT)";
    		  aar = solveGoal( parg , 2100000000, "","" , "" );
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "notifyUnexpectedObstacle";
    			if( ! aar.getGoon() ) break;
    		} 			
    		if( aar.getResult().equals("failure")){
    		if( ! switchToPlan("navigationFailure").getGoon() ) break;
    		}else if( ! aar.getGoon() ) break;
    		}
    		temporaryStr = unifyMsgContent("update(OBJECT,CURRENT)","update(OBJECT,CURRENT)", guardVars ).toString();
    		emit( "update", temporaryStr );
    		temporaryStr = " \"Unexpected Obstacle notified, I wait the new plan\" ";
    		println( temporaryStr );  
    		if( ! switchToPlan("waitConsoleCommand").getGoon() ) break;
    break;
    }//while
    return returnValue;
    }catch(Exception e){
    println( getName() + " ERROR " + e.getMessage() );
    throw e;
    }
    }
    public boolean notifyEndOfNavigation() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "notifyEndOfNavigation";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		temporaryStr = " \"è passato al piano successivo\" ";
    		println( temporaryStr );  
    		{ String parg = "notifyEnd";
    		  aar = solveGoal( parg , 10000, "","" , "" );
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "notifyEndOfNavigation";
    			if( ! aar.getGoon() ) break;
    		} 			
    		if( aar.getResult().equals("failure")){
    		if( ! switchToPlan("generalPrologFailure").getGoon() ) break;
    		}else if( ! aar.getGoon() ) break;
    		}
    		temporaryStr = " \"ma la chiama prolog fallisce per un motivo non ben definito\" ";
    		println( temporaryStr );  
    break;
    }//while
    return returnValue;
    }catch(Exception e){
    println( getName() + " ERROR " + e.getMessage() );
    throw e;
    }
    }
    public boolean handleTimeout() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "handleTimeout";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		temporaryStr = " \"timeout!! GOODBYE\" ";
    		println( temporaryStr );  
    break;
    }//while
    return returnValue;
    }catch(Exception e){
    println( getName() + " ERROR " + e.getMessage() );
    throw e;
    }
    }
    public boolean explorationFailure() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "explorationFailure";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		temporaryStr = " \"Explore FAILURE\" ";
    		println( temporaryStr );  
    break;
    }//while
    return returnValue;
    }catch(Exception e){
    println( getName() + " ERROR " + e.getMessage() );
    throw e;
    }
    }
    public boolean loadMapFailure() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "loadMapFailure";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		temporaryStr = " \"Load Map FAILURE\" ";
    		println( temporaryStr );  
    break;
    }//while
    return returnValue;
    }catch(Exception e){
    println( getName() + " ERROR " + e.getMessage() );
    throw e;
    }
    }
    public boolean findpathFailure() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "findpathFailure";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		temporaryStr = " \"Find Path FAILURE\" ";
    		println( temporaryStr );  
    break;
    }//while
    return returnValue;
    }catch(Exception e){
    println( getName() + " ERROR " + e.getMessage() );
    throw e;
    }
    }
    public boolean navigationFailure() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "navigationFailure";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		temporaryStr = " \"Navigation FAILURE\" ";
    		println( temporaryStr );  
    break;
    }//while
    return returnValue;
    }catch(Exception e){
    println( getName() + " ERROR " + e.getMessage() );
    throw e;
    }
    }
    public boolean alternativeFindpathFailure() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "alternativeFindpathFailure";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		temporaryStr = " \"Alternative Find Path FAILURE\" ";
    		println( temporaryStr );  
    break;
    }//while
    return returnValue;
    }catch(Exception e){
    println( getName() + " ERROR " + e.getMessage() );
    throw e;
    }
    }
    public boolean consultPrologFailure() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "consultPrologFailure";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		temporaryStr = " \"The consult is gone wrong, maybe there are errors in the prolog file\" ";
    		println( temporaryStr );  
    break;
    }//while
    return returnValue;
    }catch(Exception e){
    println( getName() + " ERROR " + e.getMessage() );
    throw e;
    }
    }
    public boolean generalPrologFailure() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "generalPrologFailure";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		temporaryStr = " \"Prolog goal FAILURE\" ";
    		println( temporaryStr );  
    break;
    }//while
    return returnValue;
    }catch(Exception e){
    println( getName() + " ERROR " + e.getMessage() );
    throw e;
    }
    }
    /* 
    * ------------------------------------------------------------
    * SENSORS
    * ------------------------------------------------------------
    */
    protected void initSensorSystem(){		
    	try {
    		String goal = "consult( \"./src/it/unibo/robot/sensorTheory.pl\" )";
    		AsynchActionResult aar = solveGoal( goal , 0, "","" , "" );
    		if(  aar.getResult().contains("failure")){
    			//println( "avatar initSensorSystem attempt to load sensorTheory "  );
    			goal = "consult( \"./sensorTheory.pl\" )";
    			aar = solveGoal( goal , 0, "","" , "" );
    			//println( "avatar initSensorSystem= "  +  aar.getResult() );
    		}
    		addSensorObservers();
    	} catch (Exception e) {
    		e.printStackTrace();
    	}
    }
    /*
    //COMPONENTS
     RobotComponent motorleft 
     RobotComponent motorright 
    sensor distFrontMock simulated debug=0   
    Composed component motors
    */
    protected void addSensorObservers(){
    	for (ISensor<?> sensor : Configurator.getInstance().getSensors()) {
    		//println( "robot sensor= "  + sensor.getDefStringRep() );
    		//println( "robot sensor class= "  + sensor.getClass().getName() );
        	if( sensor instanceof DistanceSensor){
        		DistanceSensor sensorDistance  = (DistanceSensor) sensor;
        		ISensorObserver<IDistanceSensorData> obs = new SensorObserver<IDistanceSensorData>(this,outView);
        //		println( "avatar add observer to  "  + sensorDistance.getDefStringRep() );
        		sensorDistance.addObserver(  obs  ) ;
        	}
        	if( sensor instanceof LineSensor){
        		LineSensor sensorLine = (LineSensor) sensor;
         		ISensorObserver<ILineSensorData> obs = new SensorObserver<ILineSensorData>(this,outView);
        //		println( "avatar add observer to  "  + sensorLine.getDefStringRep() );
        		sensorLine.addObserver(  obs  ) ;
        	}
         	if( sensor instanceof MagnetometerSensor){
        		MagnetometerSensor sensorMagneto = (MagnetometerSensor) sensor;
         		ISensorObserver<IMagnetometerSensorData> obs = new SensorObserver<IMagnetometerSensorData>(this,outView);
        //		println( "avatar add observer to  "  + sensorMagneto.getDefStringRep() );
        		sensorMagneto.addObserver(  obs  ) ;
        	}
    	//OLD	
    	}		
    }	
    
 
	/* 
	* ------------------------------------------------------------
	* APPLICATION ACTIONS
	* ------------------------------------------------------------
	*/
	
  }

