/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.console;
import it.unibo.console.gui.ConsoleGUI;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.ActorContext;

public class Console extends AbstractConsole { 
	
	
	
	
	public Console(String actorId, ActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
		((ConsoleGUI) env).setController(this);
	}
	
	@Override
	public void execAction(String cmd) {
		
		switch (cmd){
		case "LOAD":
			platform.raiseEvent("input", "local_gui_command", "command(load)");
			break;
		case "STORE":
			platform.raiseEvent("input", "local_gui_command", "command(store)");
			break;
		case "NAVIGATE":
			platform.raiseEvent("input", "local_gui_command", "command(navigate)");
			break;
		case "EXPLORE":
			platform.raiseEvent("input", "local_gui_command", "command(explore(close, 600000))");
			break;
		case "ABORT":
			platform.raiseEvent("input", "local_gui_command", "command(abort)");
			break;
		default:
			println("Invalid command");
		}
	}
	
	
}
