/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.console;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.planning.astar.algo.AStarSearchAgent;
import it.unibo.planning.astar.algo.SearchAgent;
import it.unibo.planning.astar.engine.AStarEngine;
import it.unibo.planning.astar.engine.DirAStarEngine;
import it.unibo.planning.astar.enums.Direction;
import it.unibo.planning.domain.AbstractState;
import it.unibo.planning.domain.Path;
import it.unibo.qactors.ActorContext;
import it.unibo.search.algofactory.Algo;

import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import it.unibo.console.gui.*;
import it.unibo.domain.model.implmentation.Map;

public class Console extends AbstractConsole { 
	
	private Map map;
	private it.unibo.planning.astar.algo.Path path;
	
	private int sx, sy, gx, gy;
	
	private long startLoadTime;
	
	private Algo algorithm;
	
	public Console(String actorId, ActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
		((ConsoleGUI) env).setController(this);
		path = null;
	}
	
	public void createMap(int x, int y)
	{
		map = new Map(x,y);
		startLoadTime = System.currentTimeMillis();
	}
	
	public void setMapElements(List<String> elements)
	{
		((ConsoleGUI)env).setMap(map);
	}
	
	public void setMapElements(String elements)
	{
		map.addElementsFromString(elements);
		((ConsoleGUI)env).setMap(map);
		System.out.print("Map Loading time: "+(System.currentTimeMillis()-startLoadTime));
	}
	
	public void loadMap(String path)
	{
		Map m = null;
		
		List<String> data = new ArrayList<String>();						
		try
		{
			InputStream fs = new FileInputStream(path);
			InputStreamReader inpsr = new InputStreamReader(fs);
			BufferedReader br       = new BufferedReader(inpsr);
			Iterator<String> lsit   = br.lines().iterator();

			while(lsit.hasNext())
			{
				data.add(lsit.next());
			}
			br.close();
			
		} catch (Exception e)
		{
			System.out.println("QActor  ERROR " + e.getMessage());
		}
		
		for(int i=0; i<data.size(); i++)
		{
			if(i == 0)
			{
				m = Map.createMapFromPrologRep(data.get(i));
			}
			else
			{
				String s[] = data.get(i).split(" ");
				m.addElementsFromString(s[1]);
			}
		}
		this.map = m;
		((ConsoleGUI)env).setMap(m);
	
	}
	
	public void searchBestPath(int sx, int sy, int gx, int gy, String algo)
	{		
		algorithm = Algo.fromStringValue(algo);
		
		this.sx = sx;
		this.sy = sy;
		this.gx = gx;
		this.gy = gy;
		
		/*
		SearchAgent agent = new SearchAgent();
		
		it.unibo.planning.astar.domain.State start = 
				new it.unibo.planning.astar.domain.State(sx, sy, Direction.NORTH, null, 0);
		
		it.unibo.planning.astar.domain.State goal = 
				new it.unibo.planning.astar.domain.State(gx, gy, Direction.NONE, null, 0);
		
		long st = System.currentTimeMillis();
		
		DirAStarEngine engine = new DirAStarEngine();
		engine.setIntMap(map.getIntMap(), map.getXmax(), map.getYmax());
		
		println("LET'S FIND BEST PATH");
		
		path = agent.searchBestPath(engine,start, goal);	
		*/
		
		
		AStarSearchAgent agent = new AStarSearchAgent();
		
		it.unibo.planning.astar.domain.State start = 
				new it.unibo.planning.astar.domain.State(sx, sy, null, 0);
		
		it.unibo.planning.astar.domain.State goal = 
				new it.unibo.planning.astar.domain.State(gx, gy, null, 0);
		
		long st = System.currentTimeMillis();
		
		AStarEngine engine = new AStarEngine();
		engine.setIntMap(map.getIntMap(), map.getXmax(), map.getYmax());
		
		println("LET'S FIND BEST PATH");
		
		path = agent.searchBestPath(engine,start, goal);
		
		
		println("Search Time --> " + (System.currentTimeMillis() - st) +" ms");
	}
	
	public void showPathOnGui()
	{
		((ConsoleGUI)env).setPath((ArrayList<it.unibo.planning.astar.domain.State>) path.getStates());
	}
	
	private String getPrologMap()
	{
		String data = "mapdata( "+map.toString()+" )";
		//println(data);
		return data;
	}
	
	private String getPrologPlan()
	{
		String moves = "plan("+algorithm.getValue()+", [";
		for(int i=0; i<path.getMoves().size(); i++)
		{
			moves += path.getMoves().get(i).toString();
			if(i!=path.getMoves().size()-1)
				moves+=",";
		}
		moves+="])";
		//println(moves);
		return moves;
	}
	
	private String getPrologPosition()
	{
		return "position( "+sx+", "+sy+" )";
		
	}
	

	public void sendNavigationData()
	{	
		//String pm = getPrologMap();
		String pp = getPrologPlan();
		String po = getPrologPosition();
		
		//println(pm);
		println(pp);
		println(po);
		
		//temporaryStr = unifyMsgContent("navdata(MAP,PLAN,POS)","navdata("+pm+","+pp+","+po+")", guardVars ).toString();
		
		temporaryStr = unifyMsgContent("navdata(PLAN,POS)","navdata("+pp+","+po+")", guardVars ).toString();
		println("temp string "+temporaryStr);
		try
		{
			sendMsg("navdata","robot", ActorContext.dispatch, temporaryStr );
		} catch (Exception e)
		{
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
	}
	
	
	
	@Override
	public void execAction(String cmd) {
		
		String[] command = cmd.split(" ");		
		String[] params;
		switch (command[0]){
		case "LOAD":
			platform.raiseEvent("input", "local_gui_command", "local_gui_command(loadmap(\""+command[1]+"\"))");
			break;
		
			
		case "NAVIGATE":
			platform.raiseEvent("input", "local_gui_command", "local_gui_command(navigate)");
			break;
			
		case "FIND":
			params = command[1].split(",");
			
			platform.raiseEvent("input", "local_gui_command", "local_gui_command(findpath("
						+ "position(" + params[0] + "," + params[1]+")"
								+ ","
						+ "position(" + params[2] + "," + params[3]+")"
								+ "," + params[4]
								+ "))");
						
			break;
						
		case "ABORT":
			platform.raiseEvent("input", "local_gui_command", "local_gui_command(abort)");
			break;
		default:
			println("Invalid command");
		}
	}
	
	
}
