/* Generated by AN DISI Unibo */ 
package it.unibo.console;
import alice.tuprolog.Term;
import alice.tuprolog.Struct;
import it.unibo.qactors.ActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.planned.QActorPlanned;
import it.unibo.qactors.action.ActionDummy;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.baseEnv.basicFrame.EnvFrame;
import it.unibo.console.gui.ConsoleGUI;
import alice.tuprolog.SolveInfo;
import it.unibo.is.interfaces.IActivity;
import it.unibo.is.interfaces.IIntent;

public abstract class AbstractConsole extends QActorPlanned implements IActivity{ 
	protected AsynchActionResult aar = null;
	protected boolean actionResult = true;
	protected alice.tuprolog.SolveInfo sol;
	
	protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
		//EnvFrame env = new EnvFrame( "Env_console", java.awt.Color.cyan  , java.awt.Color.black );
		//env.init();
		//env.setSize(800,400);
		
		ConsoleGUI env = new ConsoleGUI();
		env.setEnvVisible(true);
		
		//IOutputEnvView newOutEnvView = ((EnvFrame) env).getOutputEnvView();
		
		IOutputEnvView newOutEnvView = env;
		return newOutEnvView;
	}


public AbstractConsole(String actorId, ActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
	super(actorId, myCtx, "./srcMore/it/unibo/console/plans.txt", 
	"./srcMore/it/unibo/console/WorldTheory.pl",
	setTheEnv( outEnvView )  , "init");
	//addInputPanel(80);
	//addCmdPanels();	
	}
	protected void addInputPanel(int size){
		((EnvFrame) env).addInputPanel(size);			
	}
	protected void addCmdPanels(){
		((EnvFrame) env).addCmdPanel("input", new String[]{"INPUT"}, this);
		((EnvFrame) env).addCmdPanel("alarm", new String[]{"FIRE"}, this);
		((EnvFrame) env).addCmdPanel("help",  new String[]{"HELP"}, this);				
	}
		@Override
		protected void doJob() throws Exception {
	 		initSensorSystem();
			boolean res = init();
			//println(getName() + " doJob " + res );
		} 
		/* 
		* ------------------------------------------------------------
		* PLANS
		* ------------------------------------------------------------
		*/
	    public boolean init() throws Exception{	//public to allow reflection
	    try{
	    	curPlanInExec =  "init";
	    	boolean returnValue = suspendWork;
	    while(true){
	    nPlanIter++;
	    		temporaryStr = "console(start)";
	    		println( temporaryStr );  
	    		if( ! switchToPlan("waitCommand").getGoon() ) break;
	    break;
	    }//while
	    return returnValue;
	    }catch(Exception e){
	    println( getName() + " ERROR " + e.getMessage() );
	    throw e;
	    }
	    }
	    public boolean waitCommand() throws Exception{	//public to allow reflection
	    try{
	    	curPlanInExec =  "waitCommand";
	    	boolean returnValue = suspendWork;
	    while(true){
	    nPlanIter++;
	    		temporaryStr = " \"Wait for user command\" ";
	    		println( temporaryStr );  
	    		//senseEvent
	    		timeoutval = 999999999;
	    		aar = senseEvents( timeoutval,"local_gui_command","continue",
	    		"" , "",ActionExecMode.synch );
	    		if( ! aar.getGoon() || aar.getTimeRemained() <= 0 ){
	    			println("			WARNING: sense timeout");
	    			addRule("tout(senseevent,"+getName()+")");
	    			//break;
	    		}
	    		if( (guardVars = evalTheGuard( " ??tout(X,Y)" )) != null ){
	    		if( ! switchToPlan("handleTimeout").getGoon() ) break;
	    		}
	    		memoCurrentEvent( false );
	    		printCurrentEvent(false);
	    		//onEvent
	    		if( currentEvent.getEventId().equals("local_gui_command") ){
	    		 		String parg = "";
	    		 		parg = updateVars(null, Term.createTerm("command(C)"), Term.createTerm("command(explore(TYPE,MILS))"), 
	    		 			    		  					Term.createTerm(currentEvent.getMsg()), parg);
	    		 			if( parg != null ){
	    		 				 if( ! switchToPlan("exploration").getGoon() ) break; 
	    		 			}//else println("guard  fails");  //parg is null when there is no guard (onEvent)
	    		 }
	    		if( (guardVars = evalTheGuard( " !?have_map" )) != null ){
	    		//onEvent
	    		if( currentEvent.getEventId().equals("local_gui_command") ){
	    		 		String parg = "";
	    		 		parg = updateVars(guardVars, Term.createTerm("command(C)"), Term.createTerm("command(navigate(START,GOAL))"), 
	    		 			    		  					Term.createTerm(currentEvent.getMsg()), parg);
	    		 			if( parg != null ){
	    		 				 if( ! switchToPlan("navigation").getGoon() ) break; 
	    		 			}//else println("guard it.unibo.xtext.qactor.impl.GuardImpl@5f1dc7eb (name: [, not: false) fails");  //parg is null when there is no guard (onEvent)
	    		 }
	    		}
	    		if( (guardVars = evalTheGuard( " !?have_map" )) != null ){
	    		//onEvent
	    		if( currentEvent.getEventId().equals("local_gui_command") ){
	    		 		String parg = "";
	    		 		parg = updateVars(guardVars, Term.createTerm("command(C)"), Term.createTerm("command(navigate(GOAL))"), 
	    		 			    		  					Term.createTerm(currentEvent.getMsg()), parg);
	    		 			if( parg != null ){
	    		 				 if( ! switchToPlan("navigation").getGoon() ) break; 
	    		 			}//else println("guard it.unibo.xtext.qactor.impl.GuardImpl@5f51255e (name: [, not: false) fails");  //parg is null when there is no guard (onEvent)
	    		 }
	    		}
	    		//onEvent
	    		if( currentEvent.getEventId().equals("local_gui_command") ){
	    		 		String parg = "";
	    		 		parg = updateVars(null, Term.createTerm("command(C)"), Term.createTerm("command(load(PATH))"), 
	    		 			    		  					Term.createTerm(currentEvent.getMsg()), parg);
	    		 			if( parg != null ){
	    		 				 if( ! switchToPlan("loadMap").getGoon() ) break; 
	    		 			}//else println("guard  fails");  //parg is null when there is no guard (onEvent)
	    		 }
	    		if( repeatPlan(0).getGoon() ) continue;
	    break;
	    }//while
	    return returnValue;
	    }catch(Exception e){
	    println( getName() + " ERROR " + e.getMessage() );
	    throw e;
	    }
	    }
	    public boolean exploration() throws Exception{	//public to allow reflection
	    try{
	    	curPlanInExec =  "exploration";
	    	boolean returnValue = suspendWork;
	    while(true){
	    nPlanIter++;
	    		temporaryStr = " \"EXPLORE\" ";
	    		println( temporaryStr );  
	    		if( (guardVars = evalTheGuard( " ??msg(local_gui_command, \"event\" ,SENDER,none,command(explore(TYPE,MILS)),MSGNUM)" )) != null ){
	    		temporaryStr = unifyMsgContent("explore(TYPE,MILS)","explore(TYPE,MILS)", guardVars ).toString();
	    		emit( "explore", temporaryStr );
	    		}
	    		//senseEvent
	    		timeoutval = 999999999;
	    		aar = senseEvents( timeoutval,"update,local_gui_command,end","continue,continue,continue",
	    		"" , "",ActionExecMode.synch );
	    		if( ! aar.getGoon() || aar.getTimeRemained() <= 0 ){
	    			println("			WARNING: sense timeout");
	    			addRule("tout(senseevent,"+getName()+")");
	    			//break;
	    		}
	    		if( (guardVars = evalTheGuard( " ??tout(X,Y)" )) != null ){
	    		if( ! switchToPlan("handleTimeout").getGoon() ) break;
	    		}
	    		memoCurrentEvent( false );
	    		printCurrentEvent(false);
	    		//onEvent
	    		if( currentEvent.getEventId().equals("update") ){
	    		 		String parg = "";
	    		 		parg = updateVars(null, Term.createTerm("update(ELEMENT)"), Term.createTerm("update(ELEMENT)"), 
	    		 			    		  					Term.createTerm(currentEvent.getMsg()), parg);
	    		 			if( parg != null ){
	    		 				 if( ! switchToPlan("updateMap").getGoon() ) break; 
	    		 			}//else println("guard  fails");  //parg is null when there is no guard (onEvent)
	    		 }
	    		//onEvent
	    		if( currentEvent.getEventId().equals("local_gui_command") ){
	    		 		String parg = "";
	    		 		parg = updateVars(null, Term.createTerm("command(C)"), Term.createTerm("command(abort)"), 
	    		 			    		  					Term.createTerm(currentEvent.getMsg()), parg);
	    		 			if( parg != null ){
	    		 				 if( ! switchToPlan("abortLastCommand").getGoon() ) break; 
	    		 			}//else println("guard  fails");  //parg is null when there is no guard (onEvent)
	    		 }
	    		//onEvent
	    		if( currentEvent.getEventId().equals("end") ){
	    		 		String parg = "";
	    		 		parg = updateVars(null, Term.createTerm("end"), Term.createTerm("end"), 
	    		 			    		  					Term.createTerm(currentEvent.getMsg()), parg);
	    		 			if( parg != null ){
	    		 				 if( ! switchToPlan("endOfExploration").getGoon() ) break; 
	    		 			}//else println("guard  fails");  //parg is null when there is no guard (onEvent)
	    		 }
	    		if( repeatPlan(0).getGoon() ) continue;
	    break;
	    }//while
	    return returnValue;
	    }catch(Exception e){
	    println( getName() + " ERROR " + e.getMessage() );
	    throw e;
	    }
	    }
	    public boolean endOfExploration() throws Exception{	//public to allow reflection
	    try{
	    	curPlanInExec =  "endOfExploration";
	    	boolean returnValue = suspendWork;
	    while(true){
	    nPlanIter++;
	    		temporaryStr = " \"do you want to save the map or explore again??\" ";
	    		println( temporaryStr );  
	    		//senseEvent
	    		timeoutval = 999999999;
	    		aar = senseEvents( timeoutval,"local_gui_command","continue",
	    		"" , "",ActionExecMode.synch );
	    		if( ! aar.getGoon() || aar.getTimeRemained() <= 0 ){
	    			println("			WARNING: sense timeout");
	    			addRule("tout(senseevent,"+getName()+")");
	    			//break;
	    		}
	    		if( (guardVars = evalTheGuard( " ??tout(X,Y)" )) != null ){
	    		if( ! switchToPlan("handleTimeout").getGoon() ) break;
	    		}
	    		memoCurrentEvent( false );
	    		printCurrentEvent(false);
	    		//onEvent
	    		if( currentEvent.getEventId().equals("local_gui_command") ){
	    		 		String parg = "";
	    		 		parg = updateVars(null, Term.createTerm("command(C)"), Term.createTerm("command(store(PATH))"), 
	    		 			    		  					Term.createTerm(currentEvent.getMsg()), parg);
	    		 			if( parg != null ){
	    		 				 if( ! switchToPlan("storeMap").getGoon() ) break; 
	    		 			}//else println("guard  fails");  //parg is null when there is no guard (onEvent)
	    		 }
	    		//onEvent
	    		if( currentEvent.getEventId().equals("local_gui_command") ){
	    		 		String parg = "";
	    		 		parg = updateVars(null, Term.createTerm("command(C)"), Term.createTerm("command(explore(TYPE,MILS))"), 
	    		 			    		  					Term.createTerm(currentEvent.getMsg()), parg);
	    		 			if( parg != null ){
	    		 				 if( ! switchToPlan("exploration").getGoon() ) break; 
	    		 			}//else println("guard  fails");  //parg is null when there is no guard (onEvent)
	    		 }
	    break;
	    }//while
	    return returnValue;
	    }catch(Exception e){
	    println( getName() + " ERROR " + e.getMessage() );
	    throw e;
	    }
	    }
	    public boolean updateMap() throws Exception{	//public to allow reflection
	    try{
	    	curPlanInExec =  "updateMap";
	    	boolean returnValue = suspendWork;
	    while(true){
	    nPlanIter++;
	    		if( (guardVars = evalTheGuard( " ??msg(update, \"event\" ,SENDER,none,update(ELEMENT),MSGNUM)" )) != null ){
	    		temporaryStr = "update(ELEMENT)";
	    		temporaryStr = substituteVars(guardVars,temporaryStr);
	    		println( temporaryStr );  
	    		}
	    		returnValue = continueWork;  
	    break;
	    }//while
	    return returnValue;
	    }catch(Exception e){
	    println( getName() + " ERROR " + e.getMessage() );
	    throw e;
	    }
	    }
	    public boolean navigation() throws Exception{	//public to allow reflection
	    try{
	    	curPlanInExec =  "navigation";
	    	boolean returnValue = suspendWork;
	    while(true){
	    nPlanIter++;
	    		temporaryStr = " \"NAVIGATE\" ";
	    		println( temporaryStr );  
	    		if( (guardVars = evalTheGuard( " ??msg(local_gui_command, \"event\" ,SENDER,none,command(navigate(START,GOAL)),MSGNUM)" )) != null ){
	    		temporaryStr = unifyMsgContent("navigate(START,GOAL)","navigate(START,GOAL)", guardVars ).toString();
	    		emit( "navigate", temporaryStr );
	    		}
	    		if( (guardVars = evalTheGuard( " ??msg(local_gui_command, \"event\" ,SENDER,none,command(navigate(GOAL)),MSGNUM)" )) != null ){
	    		temporaryStr = unifyMsgContent("navigate(START,GOAL)","navigate(GOAL)", guardVars ).toString();
	    		emit( "navigate", temporaryStr );
	    		}
	    		//senseEvent
	    		timeoutval = 999999999;
	    		aar = senseEvents( timeoutval,"local_gui_command,end","continue,continue",
	    		"" , "",ActionExecMode.synch );
	    		if( ! aar.getGoon() || aar.getTimeRemained() <= 0 ){
	    			println("			WARNING: sense timeout");
	    			addRule("tout(senseevent,"+getName()+")");
	    			//break;
	    		}
	    		if( (guardVars = evalTheGuard( " ??tout(X,Y)" )) != null ){
	    		if( ! switchToPlan("handleTimeout").getGoon() ) break;
	    		}
	    		memoCurrentEvent( false );
	    		printCurrentEvent(false);
	    		//onEvent
	    		if( currentEvent.getEventId().equals("local_gui_command") ){
	    		 		String parg = "";
	    		 		parg = updateVars(null, Term.createTerm("command(C)"), Term.createTerm("command(abort)"), 
	    		 			    		  					Term.createTerm(currentEvent.getMsg()), parg);
	    		 			if( parg != null ){
	    		 				 if( ! switchToPlan("abortLastCommand").getGoon() ) break; 
	    		 			}//else println("guard  fails");  //parg is null when there is no guard (onEvent)
	    		 }
	    		//onEvent
	    		if( currentEvent.getEventId().equals("end") ){
	    		 		String parg = "";
	    		 		parg = updateVars(null, Term.createTerm("end"), Term.createTerm("end"), 
	    		 			    		  					Term.createTerm(currentEvent.getMsg()), parg);
	    		 			if( parg != null ){
	    		 				 if( ! switchToPlan("endOfNavigation").getGoon() ) break; 
	    		 			}//else println("guard  fails");  //parg is null when there is no guard (onEvent)
	    		 }
	    		returnValue = continueWork;  
	    break;
	    }//while
	    return returnValue;
	    }catch(Exception e){
	    println( getName() + " ERROR " + e.getMessage() );
	    throw e;
	    }
	    }
	    public boolean endOfNavigation() throws Exception{	//public to allow reflection
	    try{
	    	curPlanInExec =  "endOfNavigation";
	    	boolean returnValue = suspendWork;
	    while(true){
	    nPlanIter++;
	    		temporaryStr = " \"Robot reached the GOAL position\" ";
	    		println( temporaryStr );  
	    		if( ! switchToPlan("waitCommand").getGoon() ) break;
	    break;
	    }//while
	    return returnValue;
	    }catch(Exception e){
	    println( getName() + " ERROR " + e.getMessage() );
	    throw e;
	    }
	    }
	    public boolean loadMap() throws Exception{	//public to allow reflection
	    try{
	    	curPlanInExec =  "loadMap";
	    	boolean returnValue = suspendWork;
	    while(true){
	    nPlanIter++;
	    		temporaryStr = " \"Map loaded\" ";
	    		println( temporaryStr );  
	    		if( (guardVars = evalTheGuard( " ??msg(local_gui_command, \"event\" ,SENDER,none,command(load(PATH)),MSGNUM)" )) != null ){
	    		temporaryStr = "have_map";
	    		temporaryStr = substituteVars(guardVars,temporaryStr);
	    		addRule( temporaryStr );  
	    		}
	    		returnValue = continueWork;  
	    break;
	    }//while
	    return returnValue;
	    }catch(Exception e){
	    println( getName() + " ERROR " + e.getMessage() );
	    throw e;
	    }
	    }
	    public boolean storeMap() throws Exception{	//public to allow reflection
	    try{
	    	curPlanInExec =  "storeMap";
	    	boolean returnValue = suspendWork;
	    while(true){
	    nPlanIter++;
	    		temporaryStr = " \"Map saved\" ";
	    		println( temporaryStr );  
	    		if( (guardVars = evalTheGuard( " ??msg(local_gui_command, \"event\" ,SENDER,none,command(store(PATH)),MSGNUM)" )) != null ){
	    		temporaryStr = "have_map";
	    		temporaryStr = substituteVars(guardVars,temporaryStr);
	    		addRule( temporaryStr );  
	    		}
	    		if( ! switchToPlan("waitCommand").getGoon() ) break;
	    break;
	    }//while
	    return returnValue;
	    }catch(Exception e){
	    println( getName() + " ERROR " + e.getMessage() );
	    throw e;
	    }
	    }
	    public boolean abortLastCommand() throws Exception{	//public to allow reflection
	    try{
	    	curPlanInExec =  "abortLastCommand";
	    	boolean returnValue = suspendWork;
	    while(true){
	    nPlanIter++;
	    		temporaryStr = " \"Abort\" ";
	    		println( temporaryStr );  
	    		temporaryStr = unifyMsgContent("abort","abort", guardVars ).toString();
	    		emit( "abort", temporaryStr );
	    		if( ! switchToPlan("waitCommand").getGoon() ) break;
	    break;
	    }//while
	    return returnValue;
	    }catch(Exception e){
	    println( getName() + " ERROR " + e.getMessage() );
	    throw e;
	    }
	    }
	    public boolean handleTimeout() throws Exception{	//public to allow reflection
	    try{
	    	curPlanInExec =  "handleTimeout";
	    	boolean returnValue = suspendWork;
	    while(true){
	    nPlanIter++;
	    		temporaryStr = " \"timeout!! GOODBYE\" ";
	    		println( temporaryStr );  
	    break;
	    }//while
	    return returnValue;
	    }catch(Exception e){
	    println( getName() + " ERROR " + e.getMessage() );
	    throw e;
	    }
	    }
	    protected void initSensorSystem(){
	    	//doing nothing in a QActor
	    }
	    
	 
		/* 
		* ------------------------------------------------------------
		* APPLICATION ACTIONS
		* ------------------------------------------------------------
		*/
		
		/* 
		* ------------------------------------------------------------
		* IACTIVITY
		* ------------------------------------------------------------
		*/
		    private String[] actions = new String[]{
		    	"println( STRING | TERM )", 
		    	"play( FILENAME ) ",
		"emit(EVID,EVCONTENT)  ",
		"move(MOVE,DURATION,ANGLE)  with MOVE=mf|mb|ml|mr|ms",
		"forward( DEST, MSGID, MSGCONTENTTERM)"
		    };
		    protected void doHelp(){
				println("  GOAL ");
				println("[ GUARD ], ACTION  ");
				println("[ GUARD ], ACTION, DURATION ");
				println("[ GUARD ], ACTION, DURATION, ENDEVENT ");
				println("[ GUARD ], ACTION, DURATION,'',E VENTS, PLANS ");
				println("Actions:");
				for( int i=0; i<actions.length; i++){
					println(" " + actions[i] );
				}
		    }
		@Override
		public void execAction(String cmd) {
			if( cmd.equals("HELP") ){
				doHelp();
				return;
			}
			if( cmd.equals("FIRE") ){
				platform.raiseEvent("input", "alarm", "alarm(fire)");
				return;
			}
			String input = env.readln();
			//input = "\""+input+"\"";
			input = it.unibo.qactors.web.GuiUiKb.buildCorrectPrologString(input);
			//println("input=" + input);
			try {
				Term.createTerm(input);
				String eventMsg=it.unibo.qactors.web.QActorHttpServer.inputToEventMsg(input);
				//println("QActor eventMsg " + eventMsg);
				platform.raiseEvent("input", "local_"+it.unibo.qactors.web.GuiUiKb.inputCmd, eventMsg);
	 		} catch (Exception e) {
		 		println("QActor input error " + e.getMessage());
			}
		}
	 	
		@Override
		public void execAction() {}
		@Override
		public void execAction(IIntent input) {}
		@Override
		public String execActionWithAnswer(String cmd) {return null;}
	  }
	
