/* Generated by AN DISI Unibo */ 
package it.unibo.robot;
import java.util.ArrayList;
import java.util.List;

import it.unibo.domain.model.implmentation.Map;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.planning.astar.algo.SearchAgent;
import it.unibo.planning.astar.domain.State.Direction;
import it.unibo.qactors.ActorContext;
import it.unibo.robot.planutility.PlanSaver;
public class Robot extends AbstractRobot { 
	
	private Map map;
	private ArrayList<it.unibo.planning.astar.domain.State> path;
	
	it.unibo.planning.astar.domain.State start, goal;
	
	
	
	public Robot(String actorId, ActorContext myCtx, IOutputEnvView outEnvView ,it.unibo.iot.executors.baseRobot.IBaseRobot baserobot) throws Exception{
		super(actorId,myCtx,outEnvView ,baserobot );
		
	}
	public void createMap(int x, int y)
	{
		map = new Map(x,y);
	}
	
	public void setMapElements(List<String> elements)
	{
		map.addElementsFromList(elements);
	}
	
	public void setMapElements(String elements)
	{
		map.addElementsFromString(elements);
	}
	
	public void searchBestPath(int sx, int sy, int gx, int gy)
	{		
		SearchAgent agent = new SearchAgent();
		
		it.unibo.planning.astar.domain.State start = 
				new it.unibo.planning.astar.domain.State(sx, sy, Direction.NORTH, null, 0, map.getXmax());
		
		it.unibo.planning.astar.domain.State goal = 
				new it.unibo.planning.astar.domain.State(gx, gy, Direction.NONE, null, 0, map.getXmax());
		
		long st = System.currentTimeMillis();
		
		path = agent.searchBestStatePath(this,start, goal);	
		
		println("Search Time --> " + (System.currentTimeMillis() - st) +" ms");
	}
	
	public void showPathOnGui()
	{
		for(it.unibo.planning.astar.domain.State s : path)
		{
			System.out.println(s.toString());
		}
	}
	
	public void setNavigationPlan(String plan, int s, int t)
	{
		String speed = ""+s;
		String time = ""+t;
		
		println("Salvataggio piano in corso");
		println(plan);
		println(speed);
		println(time);
		
		PlanSaver planSaver = new PlanSaver("path");
		
		planSaver.addPrint("Inizio Navigazione");
		
		String[] moves = plan.split(",");
		
		for(String m : moves)
		{
			if(m.contains("robotmove"))
			{
				planSaver.addForwardMove(speed, time);
			}
			else
			{
				if(m.contains("left"))
				{
					planSaver.addSpinMove(speed, time, "ml");
				}
				else if(m.contains("right"))
				{
					planSaver.addSpinMove(speed, time, "mr");
				}
				else if(m.contains("doubleleft"))
				{
					planSaver.addSpinMove(speed, time, "ml");
					planSaver.addSpinMove(speed, time, "ml");
				}
				else if(m.contains("doubleright"))
				{
					planSaver.addSpinMove(speed, time, "mr");
					planSaver.addSpinMove(speed, time, "mr");
				}
			}
		}
		
		planSaver.addPrint("fine Navigazione");
		planSaver.addSolve("continueProgram", ""+0);
		
		println(planSaver.getPlan());
		planSaver.storePlan();
		
		println("PLAN SAVED IN path.txt");		
	}
	
	public void setPositions(int sx, int sy, int gx, int gy)
	{
		this.start =	new it.unibo.planning.astar.domain.State(sx, sy, Direction.NORTH, null, 0, map.getXmax());		
		this.goal =	new it.unibo.planning.astar.domain.State(gx, gy, Direction.NONE, null, 0, map.getXmax());
		
		println(start.toString());
		println(goal.toString());
	
	}
	
}
