/* Generated by AN DISI Unibo */ 
package it.unibo.robotUsage.avatar;
import it.unibo.contactEvent.interfaces.IEventItem;
import it.unibo.contactEvent.platform.EventHandlerComponent;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.ActorContext;

public class SensorEventHandler extends EventHandlerComponent { //implements IActionHandler
protected IEventItem event;
protected int count = 0;
	public SensorEventHandler(String name, ActorContext myCtx, IOutputEnvView outEnvView, String[] eventIds ) throws Exception {
		super(name, myCtx, eventIds, outEnvView);
  	}
	@Override
	public void doJob() throws Exception {
		event = getEventItem();
		if( event == null ) return;
 		showMsg( "---------------------------------------------------------------------" );	
		showMsg( event.getPrologRep()  );				 
		showMsg( "---------------------------------------------------------------------" );	
		try{
			myCtx.getActor("robot").addRule("stored("+event.getEventId()+","+event.getMsg()+")");
		}catch(Exception e){
			println("SensorEventHandler addRule ERROR " + e.getMessage());
		}
 		/*
		 * Test interaction with the uniboArduinBaseoSupport program
		 */
		count++;
		if( count == 5){
			println("%%%%%%%%%%% sendCmdToDevice d%%%%%%%%%%%%%%");
			it.unibo.iot.device.serial.impl.SerialIOManager.sendCmdToDevice('r'); //reset
			it.unibo.iot.device.serial.impl.SerialIOManager.sendCmdToDevice('s'); //sonar distance
		}

	}
	

 
}
