/* Generated by AN DISI Unibo */ 
package it.unibo.robot;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.QActorUtils;
import it.unibo.qactors.akka.QActorPlanUtils;

//
public class Robot extends AbstractRobot { 
	public Robot(String actorId, QActorContext myCtx, IOutputEnvView outEnvView ) throws Exception{
		super(actorId,myCtx,outEnvView ,it.unibo.qactors.QActorUtils.robotBase );
		
		QActorPlanUtils myUtils = new QActorPlanUtilsDebug(this, actionUtils, outEnvView);
		((QActorPlanUtilsDebug) myUtils).setUnitySimulation(true);
		this.planUtils = myUtils;
	}
	
	public void consultFromFile(String filename)
	{
		System.out.println("loading...");
		QActorUtils.consultFromFile(pengine, filename);
	}	
	
	public void stampaRoba(){
		println("ROBAAAAAA");
	}
}
