/* Generated by AN DISI Unibo */ 
package it.unibo.robot;
import alice.tuprolog.SolveInfo;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.action.ActionReceiveTimed;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.iot.configurator.Configurator;
import it.unibo.iot.executors.baseRobot.IBaseRobot; 
import it.unibo.iot.models.sensorData.distance.IDistanceSensorData;
import it.unibo.iot.models.sensorData.impact.IImpactSensorData;
import it.unibo.iot.models.sensorData.line.ILineSensorData;
import it.unibo.iot.models.sensorData.magnetometer.IMagnetometerSensorData;
import it.unibo.iot.sensors.ISensor; 
import it.unibo.iot.sensors.ISensorObserver;
import it.unibo.iot.sensors.distanceSensor.DistanceSensor;
import it.unibo.iot.sensors.impactSensor.ImpactSensor;
import it.unibo.iot.sensors.lineSensor.LineSensor;
import it.unibo.iot.sensors.magnetometerSensor.MagnetometerSensor;
import it.unibo.qactors.action.IMsgQueue;
import it.unibo.qactors.QActorMessage;
import it.unibo.qactors.QActorUtils;


class QaRobotActor extends it.unibo.qactor.robot.RobotActor{
	public QaRobotActor(
		String name, QActorContext ctx, String worldTheoryPath,
			IOutputEnvView outEnvView, String baserobot, String defaultPlan )  throws Exception{
		super(name, ctx, "./srcMore/it/unibo/robot/plans.txt", worldTheoryPath,
		outEnvView, it.unibo.qactor.robot.RobotSysKb.setRobotBase(ctx, baserobot) , defaultPlan);
	}
}

public class AbstractRobot extends QaRobotActor { 
protected AsynchActionResult aar = null;
protected boolean actionResult = true;
protected alice.tuprolog.SolveInfo sol;
//protected IMsgQueue mysupport ;  //defined in QActor
protected String planFilePath    = null;
protected String terminationEvId = "default";
protected String parg="";
protected boolean bres=false;
protected IActorAction  action;

		protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
			return outEnvView;
		}


	public AbstractRobot(String actorId, QActorContext myCtx, IOutputEnvView outEnvView ,String baserobot)  throws Exception{
		super(actorId, myCtx,  
		"./srcMore/it/unibo/robot/WorldTheory.pl",
		setTheEnv( outEnvView ) ,baserobot , "init");		
		this.planFilePath = "./srcMore/it/unibo/robot/plans.txt";
		//Plan interpretation is done in Prolog
		//if(planFilePath != null) planUtils.buildPlanTable(planFilePath);
 	}
	@Override
	protected void doJob() throws Exception {
		String name  = getName().replace("_ctrl", "");
		mysupport = (IMsgQueue) QActorUtils.getQActor( name );
 		initSensorSystem();
		boolean res = init();
		//println(getName() + " doJob " + res );
	} 
	/* 
	* ------------------------------------------------------------
	* PLANS
	* ------------------------------------------------------------
	*/
    public boolean init() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "init";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		parg = "consult(\"robotTheory.pl\")";
    		//REGENERATE AKKA
    		aar = solveGoalReactive(parg,210000000,"","");
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "init";
    			if( ! aar.getGoon() ) break;
    		} 			
    		parg = "consult(\"navRobotTheory.pl\")";
    		//REGENERATE AKKA
    		aar = solveGoalReactive(parg,210000000,"","");
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "init";
    			if( ! aar.getGoon() ) break;
    		} 			
    		parg = "consult(\"expRobotTheory.pl\")";
    		//REGENERATE AKKA
    		aar = solveGoalReactive(parg,210000000,"","");
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "init";
    			if( ! aar.getGoon() ) break;
    		} 			
    		parg = "consult(\"talkTheory.pl\")";
    		//REGENERATE AKKA
    		aar = solveGoalReactive(parg,210000000,"","");
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "init";
    			if( ! aar.getGoon() ) break;
    		} 			
    		temporaryStr = "\"++++++++++++++++++ robot(starts) ++++++++++++++++++\"";
    		println( temporaryStr );  
    		if( ! planUtils.switchToPlan("waitConsoleCommand").getGoon() ) break;
    break;
    }//while
    return returnValue;
    }catch(Exception e){
       //println( getName() + " plan=init WARNING:" + e.getMessage() );
       QActorContext.terminateQActorSystem(this); 
       return false;  
    }
    }
    public boolean waitConsoleCommand() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "waitConsoleCommand";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		temporaryStr = "\"++++++++++++++++++ WAIT CONSOLE COMMAND ++++++++++++++++++\"";
    		println( temporaryStr );  
    		//ReceiveMsg
    		 		 aar = planUtils.receiveAMsg(mysupport,600000000, "" , "" ); 	//could block
    				if( aar.getInterrupted() ){
    					curPlanInExec   = "playTheGame";
    					if( ! aar.getGoon() ) break;
    				} 			
    				//if( ! aar.getGoon() ){
    					//System.out.println("			WARNING: receiveMsg in " + getName() + " TOUT " + aar.getTimeRemained() + "/" +  600000000);
    					//addRule("tout(receive,"+getName()+")");
    				//} 		 
    				//println(getName() + " received " + aar.getResult() );
    		printCurrentMessage(false);
    		memoCurrentMessage( false );
    		//onMsg
    		if( currentMessage.msgId().equals("explore") ){
    			String parg = "";
    			/* SwitchPlan */
    			parg =  updateVars(  Term.createTerm("explore"), Term.createTerm("explore"), 
    				    		  					Term.createTerm(currentMessage.msgContent()), parg);
    				if( parg != null ){
    					 if( ! planUtils.switchToPlan("exploration").getGoon() ) break; 
    				}//else println("guard  fails");  //parg is null when there is no guard (onEvent)
    		}//onMsg
    		if( currentMessage.msgId().equals("explore") ){
    			String parg = "";
    			/* SwitchPlan */
    			parg =  updateVars(  Term.createTerm("explore"), Term.createTerm("explore(START,BOUNDS)"), 
    				    		  					Term.createTerm(currentMessage.msgContent()), parg);
    				if( parg != null ){
    					 if( ! planUtils.switchToPlan("explorationDebug").getGoon() ) break; 
    				}//else println("guard  fails");  //parg is null when there is no guard (onEvent)
    		}//onMsg
    		if( currentMessage.msgId().equals("navigate") ){
    			String parg = "";
    			/* SwitchPlan */
    			parg =  updateVars(  Term.createTerm("navigate(PLAN,POS)"), Term.createTerm("navigate(PLAN,POS)"), 
    				    		  					Term.createTerm(currentMessage.msgContent()), parg);
    				if( parg != null ){
    					 if( ! planUtils.switchToPlan("navigation").getGoon() ) break; 
    				}//else println("guard  fails");  //parg is null when there is no guard (onEvent)
    		}if( planUtils.repeatPlan(0).getGoon() ) continue;
    break;
    }//while
    return returnValue;
    }catch(Exception e){
       //println( getName() + " plan=waitConsoleCommand WARNING:" + e.getMessage() );
       QActorContext.terminateQActorSystem(this); 
       return false;  
    }
    }
    public boolean exploration() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "exploration";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		temporaryStr = "\"\"";
    		println( temporaryStr );  
    break;
    }//while
    return returnValue;
    }catch(Exception e){
       //println( getName() + " plan=exploration WARNING:" + e.getMessage() );
       QActorContext.terminateQActorSystem(this); 
       return false;  
    }
    }
    public boolean explorationDebug() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "explorationDebug";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		temporaryStr = "\"Let's explore!!\"";
    		println( temporaryStr );  
    		if( (guardVars = QActorUtils.evalTheGuard(this, " ??msg(_,_,SENDER,X,explore(START,BOUNDS),MSGNUM)" )) != null ){
    		parg = "initExploreMap(START,BOUNDS)";
    		parg = QActorUtils.substituteVars(guardVars,parg);
    		//REGENERATE AKKA
    		aar = solveGoalReactive(parg,0,"","");
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "explorationDebug";
    			if( ! aar.getGoon() ) break;
    		} 			
    		}
    		if( ! planUtils.switchToPlan("notifyCell").getGoon() ) break;
    		parg = "assert(explore(true))";
    		//REGENERATE AKKA
    		aar = solveGoalReactive(parg,0,"","");
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "explorationDebug";
    			if( ! aar.getGoon() ) break;
    		} 			
    		if( ! planUtils.switchToPlan("findLeftWall").getGoon() ) break;
    break;
    }//while
    return returnValue;
    }catch(Exception e){
       //println( getName() + " plan=explorationDebug WARNING:" + e.getMessage() );
       QActorContext.terminateQActorSystem(this); 
       return false;  
    }
    }
    public boolean findLeftWall() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "findLeftWall";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		temporaryStr = "\"Find Left Wall!\"";
    		println( temporaryStr );  
    		//senseEvent
    		timeoutval = 1000;
    		aar = planUtils.senseEvents( timeoutval,"obstacle","continue",
    		"" , "",ActionExecMode.synch );
    		if( ! aar.getGoon() || aar.getTimeRemained() <= 0 ){
    			//println("			WARNING: sense timeout");
    			addRule("tout(senseevent,"+getName()+")");
    			//break;
    		}
    		//onEvent
    		if( currentEvent.getEventId().equals("obstacle") ){
    		 		String parg="assert(obstacle(front,obstacle))";
    		 		/* PHead */
    		 		parg =  updateVars( Term.createTerm("obstacle(DIRECTION)"), Term.createTerm("obstacle(front)"), 
    		 			    		  					Term.createTerm(currentEvent.getMsg()), parg);
    		 			if( parg != null ) {
    		 			    aar = QActorUtils.solveGoal(this,myCtx,pengine,parg,"",outEnvView,0);
    		 				//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		 				if( aar.getInterrupted() ){
    		 					curPlanInExec   = "findLeftWall";
    		 					if( ! aar.getGoon() ) break;
    		 				} 			
    		 				if( aar.getResult().equals("failure")){
    		 					if( ! aar.getGoon() ) break;
    		 				}else if( ! aar.getGoon() ) break;
    		 			}
    		 }
    		else{ parg = "assert(obstacle(front,clear))";
    		//REGENERATE AKKA
    		aar = solveGoalReactive(parg,0,"","");
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "findLeftWall";
    			if( ! aar.getGoon() ) break;
    		} 			
    		}if( (guardVars = QActorUtils.evalTheGuard(this, " !?obstacle(front,clear)" )) != null ){
    		parg = "updateModel(front,clear)";
    		parg = QActorUtils.substituteVars(guardVars,parg);
    		//REGENERATE AKKA
    		aar = solveGoalReactive(parg,0,"","");
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "findLeftWall";
    			if( ! aar.getGoon() ) break;
    		} 			
    		}
    		if( (guardVars = QActorUtils.evalTheGuard(this, " ??obstacle(front,clear)" )) != null ){
    		if( ! planUtils.switchToPlan("notifyCell").getGoon() ) break;
    		}
    		if( (guardVars = QActorUtils.evalTheGuard(this, " !?obstacle(front,obstacle)" )) != null ){
    		parg = "updateModel(front,obstacle)";
    		parg = QActorUtils.substituteVars(guardVars,parg);
    		//REGENERATE AKKA
    		aar = solveGoalReactive(parg,0,"","");
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "findLeftWall";
    			if( ! aar.getGoon() ) break;
    		} 			
    		}
    		if( (guardVars = QActorUtils.evalTheGuard(this, " !?obstacle(front,obstacle)" )) != null ){
    		if( ! planUtils.switchToPlan("notifyCell").getGoon() ) break;
    		}
    		if( (guardVars = QActorUtils.evalTheGuard(this, " ??obstacle(front,obstacle)" )) != null ){
    		if( ! planUtils.switchToPlan("turnRightAndFollow").getGoon() ) break;
    		}
    		//senseEvent
    		timeoutval = 1000;
    		aar = planUtils.senseEvents( timeoutval,"obstacle","continue",
    		"" , "",ActionExecMode.synch );
    		if( ! aar.getGoon() || aar.getTimeRemained() <= 0 ){
    			//println("			WARNING: sense timeout");
    			addRule("tout(senseevent,"+getName()+")");
    			//break;
    		}
    		//onEvent
    		if( currentEvent.getEventId().equals("obstacle") ){
    		 		String parg="assert(obstacle(left,obstacle))";
    		 		/* PHead */
    		 		parg =  updateVars( Term.createTerm("obstacle(DIRECTION)"), Term.createTerm("obstacle(left)"), 
    		 			    		  					Term.createTerm(currentEvent.getMsg()), parg);
    		 			if( parg != null ) {
    		 			    aar = QActorUtils.solveGoal(this,myCtx,pengine,parg,"",outEnvView,0);
    		 				//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		 				if( aar.getInterrupted() ){
    		 					curPlanInExec   = "findLeftWall";
    		 					if( ! aar.getGoon() ) break;
    		 				} 			
    		 				if( aar.getResult().equals("failure")){
    		 					if( ! aar.getGoon() ) break;
    		 				}else if( ! aar.getGoon() ) break;
    		 			}
    		 }
    		else{ parg = "assert(obstacle(left,clear))";
    		//REGENERATE AKKA
    		aar = solveGoalReactive(parg,0,"","");
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "findLeftWall";
    			if( ! aar.getGoon() ) break;
    		} 			
    		}if( (guardVars = QActorUtils.evalTheGuard(this, " !?obstacle(left,clear)" )) != null ){
    		parg = "updateModel(left,clear)";
    		parg = QActorUtils.substituteVars(guardVars,parg);
    		//REGENERATE AKKA
    		aar = solveGoalReactive(parg,0,"","");
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "findLeftWall";
    			if( ! aar.getGoon() ) break;
    		} 			
    		}
    		if( (guardVars = QActorUtils.evalTheGuard(this, " ??obstacle(left,clear)" )) != null ){
    		if( ! planUtils.switchToPlan("notifyCell").getGoon() ) break;
    		}
    		if( (guardVars = QActorUtils.evalTheGuard(this, " !?obstacle(left,obstacle)" )) != null ){
    		parg = "updateModel(left,obstacle)";
    		parg = QActorUtils.substituteVars(guardVars,parg);
    		//REGENERATE AKKA
    		aar = solveGoalReactive(parg,0,"","");
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "findLeftWall";
    			if( ! aar.getGoon() ) break;
    		} 			
    		}
    		if( (guardVars = QActorUtils.evalTheGuard(this, " !?obstacle(left,obstacle)" )) != null ){
    		if( ! planUtils.switchToPlan("notifyCell").getGoon() ) break;
    		}
    		if( (guardVars = QActorUtils.evalTheGuard(this, " ??obstacle(left,obstacle)" )) != null ){
    		if( ! planUtils.switchToPlan("followWall").getGoon() ) break;
    		}
    		temporaryStr = "\"Forward Step\"";
    		println( temporaryStr );  
    		parg = "moveForward";
    		//REGENERATE AKKA
    		aar = solveGoalReactive(parg,10000000,"","");
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "findLeftWall";
    			if( ! aar.getGoon() ) break;
    		} 			
    		parg = "addCurrentToVisited";
    		//REGENERATE AKKA
    		aar = solveGoalReactive(parg,10000000,"","");
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "findLeftWall";
    			if( ! aar.getGoon() ) break;
    		} 			
    		if( planUtils.repeatPlan(0).getGoon() ) continue;
    break;
    }//while
    return returnValue;
    }catch(Exception e){
       //println( getName() + " plan=findLeftWall WARNING:" + e.getMessage() );
       QActorContext.terminateQActorSystem(this); 
       return false;  
    }
    }
    public boolean turnRightAndFollow() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "turnRightAndFollow";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		temporaryStr = "\"turn right and follow\"";
    		println( temporaryStr );  
    		parg = "turnDoubleRight";
    		//REGENERATE AKKA
    		aar = solveGoalReactive(parg,0,"","");
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "turnRightAndFollow";
    			if( ! aar.getGoon() ) break;
    		} 			
    		if( ! planUtils.switchToPlan("followWall").getGoon() ) break;
    break;
    }//while
    return returnValue;
    }catch(Exception e){
       //println( getName() + " plan=turnRightAndFollow WARNING:" + e.getMessage() );
       QActorContext.terminateQActorSystem(this); 
       return false;  
    }
    }
    public boolean turnLeftAndFind() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "turnLeftAndFind";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		temporaryStr = "\"Wall Found!! - Left\"";
    		println( temporaryStr );  
    		parg = "turnDoubleLeft";
    		//REGENERATE AKKA
    		aar = solveGoalReactive(parg,0,"","");
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "turnLeftAndFind";
    			if( ! aar.getGoon() ) break;
    		} 			
    		if( ! planUtils.switchToPlan("findLeftWall").getGoon() ) break;
    break;
    }//while
    return returnValue;
    }catch(Exception e){
       //println( getName() + " plan=turnLeftAndFind WARNING:" + e.getMessage() );
       QActorContext.terminateQActorSystem(this); 
       return false;  
    }
    }
    public boolean turnLeft() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "turnLeft";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		temporaryStr = "\"turn Left\"";
    		println( temporaryStr );  
    		parg = "turnDoubleLeft";
    		//REGENERATE AKKA
    		aar = solveGoalReactive(parg,0,"","");
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "turnLeft";
    			if( ! aar.getGoon() ) break;
    		} 			
    		returnValue = continueWork;  
    break;
    }//while
    return returnValue;
    }catch(Exception e){
       //println( getName() + " plan=turnLeft WARNING:" + e.getMessage() );
       QActorContext.terminateQActorSystem(this); 
       return false;  
    }
    }
    public boolean turnRight() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "turnRight";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		temporaryStr = "\"turn Right\"";
    		println( temporaryStr );  
    		parg = "turnDoubleLeft";
    		//REGENERATE AKKA
    		aar = solveGoalReactive(parg,0,"","");
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "turnRight";
    			if( ! aar.getGoon() ) break;
    		} 			
    		returnValue = continueWork;  
    break;
    }//while
    return returnValue;
    }catch(Exception e){
       //println( getName() + " plan=turnRight WARNING:" + e.getMessage() );
       QActorContext.terminateQActorSystem(this); 
       return false;  
    }
    }
    public boolean followWall() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "followWall";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		temporaryStr = "\"Follow Wall\"";
    		println( temporaryStr );  
    		//senseEvent
    		timeoutval = 1000;
    		aar = planUtils.senseEvents( timeoutval,"obstacle","continue",
    		"" , "",ActionExecMode.synch );
    		if( ! aar.getGoon() || aar.getTimeRemained() <= 0 ){
    			//println("			WARNING: sense timeout");
    			addRule("tout(senseevent,"+getName()+")");
    			//break;
    		}
    		//onEvent
    		if( currentEvent.getEventId().equals("obstacle") ){
    		 		String parg="assert(obstacle(left,object))";
    		 		/* PHead */
    		 		parg =  updateVars( Term.createTerm("obstacle(DIRECTION)"), Term.createTerm("obstacle(left)"), 
    		 			    		  					Term.createTerm(currentEvent.getMsg()), parg);
    		 			if( parg != null ) {
    		 			    aar = QActorUtils.solveGoal(this,myCtx,pengine,parg,"",outEnvView,0);
    		 				//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		 				if( aar.getInterrupted() ){
    		 					curPlanInExec   = "followWall";
    		 					if( ! aar.getGoon() ) break;
    		 				} 			
    		 				if( aar.getResult().equals("failure")){
    		 					if( ! aar.getGoon() ) break;
    		 				}else if( ! aar.getGoon() ) break;
    		 			}
    		 }
    		else{ parg = "assert(obstacle(left,clear))";
    		//REGENERATE AKKA
    		aar = solveGoalReactive(parg,0,"","");
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "followWall";
    			if( ! aar.getGoon() ) break;
    		} 			
    		}if( (guardVars = QActorUtils.evalTheGuard(this, " !?obstacle(left,clear)" )) != null ){
    		parg = "updateModel(left,clear)";
    		parg = QActorUtils.substituteVars(guardVars,parg);
    		//REGENERATE AKKA
    		aar = solveGoalReactive(parg,0,"","");
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "followWall";
    			if( ! aar.getGoon() ) break;
    		} 			
    		}
    		if( (guardVars = QActorUtils.evalTheGuard(this, " ??obstacle(left,clear)" )) != null ){
    		if( ! planUtils.switchToPlan("notifyCell").getGoon() ) break;
    		}
    		if( (guardVars = QActorUtils.evalTheGuard(this, " !?obstacle(left,object)" )) != null ){
    		parg = "updateModel(left,object)";
    		parg = QActorUtils.substituteVars(guardVars,parg);
    		//REGENERATE AKKA
    		aar = solveGoalReactive(parg,0,"","");
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "followWall";
    			if( ! aar.getGoon() ) break;
    		} 			
    		}
    		if( (guardVars = QActorUtils.evalTheGuard(this, " !?obstacle(left,object)" )) != null ){
    		if( ! planUtils.switchToPlan("notifyCell").getGoon() ) break;
    		}
    		if( (guardVars = QActorUtils.evalTheGuard(this, " ??obstacle(left,object)" )) != null ){
    		if( ! planUtils.switchToPlan("turnLeftAndFind").getGoon() ) break;
    		}
    		//senseEvent
    		timeoutval = 1000;
    		aar = planUtils.senseEvents( timeoutval,"obstacle","continue",
    		"" , "",ActionExecMode.synch );
    		if( ! aar.getGoon() || aar.getTimeRemained() <= 0 ){
    			//println("			WARNING: sense timeout");
    			addRule("tout(senseevent,"+getName()+")");
    			//break;
    		}
    		//onEvent
    		if( currentEvent.getEventId().equals("obstacle") ){
    		 		String parg="assert(obstacle(front,object))";
    		 		/* PHead */
    		 		parg =  updateVars( Term.createTerm("obstacle(DIRECTION)"), Term.createTerm("obstacle(front)"), 
    		 			    		  					Term.createTerm(currentEvent.getMsg()), parg);
    		 			if( parg != null ) {
    		 			    aar = QActorUtils.solveGoal(this,myCtx,pengine,parg,"",outEnvView,0);
    		 				//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		 				if( aar.getInterrupted() ){
    		 					curPlanInExec   = "followWall";
    		 					if( ! aar.getGoon() ) break;
    		 				} 			
    		 				if( aar.getResult().equals("failure")){
    		 					if( ! aar.getGoon() ) break;
    		 				}else if( ! aar.getGoon() ) break;
    		 			}
    		 }
    		else{ parg = "assert(obstacle(front,clear))";
    		//REGENERATE AKKA
    		aar = solveGoalReactive(parg,0,"","");
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "followWall";
    			if( ! aar.getGoon() ) break;
    		} 			
    		}if( (guardVars = QActorUtils.evalTheGuard(this, " !?obstacle(front,clear)" )) != null ){
    		parg = "updateModel(front,clear)";
    		parg = QActorUtils.substituteVars(guardVars,parg);
    		//REGENERATE AKKA
    		aar = solveGoalReactive(parg,0,"","");
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "followWall";
    			if( ! aar.getGoon() ) break;
    		} 			
    		}
    		if( (guardVars = QActorUtils.evalTheGuard(this, " !?obstacle(front,clear)" )) != null ){
    		if( ! planUtils.switchToPlan("notifyCell").getGoon() ) break;
    		}
    		if( (guardVars = QActorUtils.evalTheGuard(this, " ??obstacle(front,clear)" )) != null ){
    		if( ! planUtils.switchToPlan("moveAndCheckLoop").getGoon() ) break;
    		}
    		if( (guardVars = QActorUtils.evalTheGuard(this, " !?obstacle(front,object)" )) != null ){
    		parg = "updateModel(front,object)";
    		parg = QActorUtils.substituteVars(guardVars,parg);
    		//REGENERATE AKKA
    		aar = solveGoalReactive(parg,0,"","");
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "followWall";
    			if( ! aar.getGoon() ) break;
    		} 			
    		}
    		if( (guardVars = QActorUtils.evalTheGuard(this, " !?obstacle(front,object)" )) != null ){
    		if( ! planUtils.switchToPlan("notifyCell").getGoon() ) break;
    		}
    		if( (guardVars = QActorUtils.evalTheGuard(this, " ??obstacle(front,object)" )) != null ){
    		if( ! planUtils.switchToPlan("frontWallFound").getGoon() ) break;
    		}
    		if( planUtils.repeatPlan(0).getGoon() ) continue;
    break;
    }//while
    return returnValue;
    }catch(Exception e){
       //println( getName() + " plan=followWall WARNING:" + e.getMessage() );
       QActorContext.terminateQActorSystem(this); 
       return false;  
    }
    }
    public boolean frontWallFound() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "frontWallFound";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		temporaryStr = "\"I hit a wall\"";
    		println( temporaryStr );  
    		//senseEvent
    		timeoutval = 1000;
    		aar = planUtils.senseEvents( timeoutval,"obstacle","continue",
    		"" , "",ActionExecMode.synch );
    		if( ! aar.getGoon() || aar.getTimeRemained() <= 0 ){
    			//println("			WARNING: sense timeout");
    			addRule("tout(senseevent,"+getName()+")");
    			//break;
    		}
    		//onEvent
    		if( currentEvent.getEventId().equals("obstacle") ){
    		 		String parg="assert(obstacle(left,object))";
    		 		/* PHead */
    		 		parg =  updateVars( Term.createTerm("obstacle(DIRECTION)"), Term.createTerm("obstacle(left)"), 
    		 			    		  					Term.createTerm(currentEvent.getMsg()), parg);
    		 			if( parg != null ) {
    		 			    aar = QActorUtils.solveGoal(this,myCtx,pengine,parg,"",outEnvView,0);
    		 				//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		 				if( aar.getInterrupted() ){
    		 					curPlanInExec   = "frontWallFound";
    		 					if( ! aar.getGoon() ) break;
    		 				} 			
    		 				if( aar.getResult().equals("failure")){
    		 					if( ! aar.getGoon() ) break;
    		 				}else if( ! aar.getGoon() ) break;
    		 			}
    		 }
    		else{ parg = "assert(obstacle(left,clear))";
    		//REGENERATE AKKA
    		aar = solveGoalReactive(parg,0,"","");
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "frontWallFound";
    			if( ! aar.getGoon() ) break;
    		} 			
    		}if( (guardVars = QActorUtils.evalTheGuard(this, " !?obstacle(left,clear)" )) != null ){
    		parg = "updateModel(left,clear)";
    		parg = QActorUtils.substituteVars(guardVars,parg);
    		//REGENERATE AKKA
    		aar = solveGoalReactive(parg,0,"","");
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "frontWallFound";
    			if( ! aar.getGoon() ) break;
    		} 			
    		}
    		if( (guardVars = QActorUtils.evalTheGuard(this, " !?obstacle(left,clear)" )) != null ){
    		if( ! planUtils.switchToPlan("notifyCell").getGoon() ) break;
    		}
    		if( (guardVars = QActorUtils.evalTheGuard(this, " !?obstacle(left,object)" )) != null ){
    		parg = "updateModel(left,object)";
    		parg = QActorUtils.substituteVars(guardVars,parg);
    		//REGENERATE AKKA
    		aar = solveGoalReactive(parg,0,"","");
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "frontWallFound";
    			if( ! aar.getGoon() ) break;
    		} 			
    		}
    		if( (guardVars = QActorUtils.evalTheGuard(this, " !?obstacle(left,object)" )) != null ){
    		if( ! planUtils.switchToPlan("notifyCell").getGoon() ) break;
    		}
    		parg = "senseAndCheckLeft";
    		//REGENERATE AKKA
    		aar = solveGoalReactive(parg,1000000,"","");
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "frontWallFound";
    			if( ! aar.getGoon() ) break;
    		} 			
    		if( (guardVars = QActorUtils.evalTheGuard(this, " !?notLeftObjectAndNotExplored(true)" )) != null ){
    		if( ! planUtils.switchToPlan("turnLeft").getGoon() ) break;
    		}
    		else{ if( ! planUtils.switchToPlan("turnRight").getGoon() ) break;
    		}returnValue = continueWork; //we must restore nPlanIter and curPlanInExec of the 'interrupted' plan
    break;
    }//while
    return returnValue;
    }catch(Exception e){
       //println( getName() + " plan=frontWallFound WARNING:" + e.getMessage() );
       QActorContext.terminateQActorSystem(this); 
       return false;  
    }
    }
    public boolean moveAndCheckLoop() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "moveAndCheckLoop";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		temporaryStr = "\"let's move\"";
    		println( temporaryStr );  
    		parg = "moveForward";
    		//REGENERATE AKKA
    		aar = solveGoalReactive(parg,100000,"","");
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "moveAndCheckLoop";
    			if( ! aar.getGoon() ) break;
    		} 			
    		parg = "checkCurrentAlreadyVisited";
    		//REGENERATE AKKA
    		aar = solveGoalReactive(parg,100000,"","");
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "moveAndCheckLoop";
    			if( ! aar.getGoon() ) break;
    		} 			
    		if( (guardVars = QActorUtils.evalTheGuard(this, " !?currentAlreadyVisited(false)" )) != null ){
    		if( ! planUtils.switchToPlan("loopAvoidance").getGoon() ) break;
    		}
    		else{ parg = "addCurrentToVisited";
    		parg = QActorUtils.substituteVars(guardVars,parg);
    		//REGENERATE AKKA
    		aar = solveGoalReactive(parg,10000000,"","");
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "moveAndCheckLoop";
    			if( ! aar.getGoon() ) break;
    		} 			
    		}returnValue = continueWork; //we must restore nPlanIter and curPlanInExec of the 'interrupted' plan
    break;
    }//while
    return returnValue;
    }catch(Exception e){
       //println( getName() + " plan=moveAndCheckLoop WARNING:" + e.getMessage() );
       QActorContext.terminateQActorSystem(this); 
       return false;  
    }
    }
    public boolean loopAvoidance() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "loopAvoidance";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		temporaryStr = "\"I'm in a looooop\"";
    		println( temporaryStr );  
    		parg = "findNearestNotExploredCell";
    		//REGENERATE AKKA
    		aar = solveGoalReactive(parg,1000000,"","");
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "loopAvoidance";
    			if( ! aar.getGoon() ) break;
    		} 			
    		if( (guardVars = QActorUtils.evalTheGuard(this, " !?explore(false)" )) != null ){
    		if( ! planUtils.switchToPlan("endOfExploration").getGoon() ) break;
    		}
    		parg = "computeBestPath";
    		//REGENERATE AKKA
    		aar = solveGoalReactive(parg,1000000000,"","");
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "loopAvoidance";
    			if( ! aar.getGoon() ) break;
    		} 			
    		parg = "travel";
    		//REGENERATE AKKA
    		aar = solveGoalReactive(parg,1000000000,"","");
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "loopAvoidance";
    			if( ! aar.getGoon() ) break;
    		} 			
    		if( ! planUtils.switchToPlan("findLeftWall").getGoon() ) break;
    break;
    }//while
    return returnValue;
    }catch(Exception e){
       //println( getName() + " plan=loopAvoidance WARNING:" + e.getMessage() );
       QActorContext.terminateQActorSystem(this); 
       return false;  
    }
    }
    public boolean notifyCell() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "notifyCell";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		temporaryStr = "\"notify clear cell\"";
    		println( temporaryStr );  
    		if( (guardVars = QActorUtils.evalTheGuard(this, " ??newCell(POS,STATE)" )) != null ){
    		temporaryStr = QActorUtils.unifyMsgContent(pengine, "expdata(POS,STATE)","expdata(POS,STATE)", guardVars ).toString();
    		emit( "expdata", temporaryStr );
    		}
    		returnValue = continueWork;  
    break;
    }//while
    return returnValue;
    }catch(Exception e){
       //println( getName() + " plan=notifyCell WARNING:" + e.getMessage() );
       QActorContext.terminateQActorSystem(this); 
       return false;  
    }
    }
    public boolean endOfExploration() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "endOfExploration";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		temporaryStr = "\"Exploration done\"";
    		println( temporaryStr );  
    break;
    }//while
    return returnValue;
    }catch(Exception e){
       //println( getName() + " plan=endOfExploration WARNING:" + e.getMessage() );
       QActorContext.terminateQActorSystem(this); 
       return false;  
    }
    }
    public boolean navigation() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "navigation";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		temporaryStr = "\"I Received some navigation data\"";
    		println( temporaryStr );  
    		if( (guardVars = QActorUtils.evalTheGuard(this, " ??msg(_,_,SENDER,X,navigate(PLAN,POS),MSGNUM)" )) != null ){
    		parg = "loadNavigationData(PLAN,POS)";
    		parg = QActorUtils.substituteVars(guardVars,parg);
    		//REGENERATE AKKA
    		aar = solveGoalReactive(parg,100000,"","");
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "navigation";
    			if( ! aar.getGoon() ) break;
    		} 			
    		}
    		if( ! planUtils.switchToPlan("startNavigation").getGoon() ) break;
    break;
    }//while
    return returnValue;
    }catch(Exception e){
       //println( getName() + " plan=navigation WARNING:" + e.getMessage() );
       QActorContext.terminateQActorSystem(this); 
       return false;  
    }
    }
    public boolean startNavigation() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "startNavigation";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		if( (guardVars = QActorUtils.evalTheGuard(this, " !?planFilename(FILENAME)" )) != null ){
    		parg = "loadThePlan(FILENAME)";
    		parg = QActorUtils.substituteVars(guardVars,parg);
    		//REGENERATE AKKA
    		aar = solveGoalReactive(parg,300000000,"","");
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "startNavigation";
    			if( ! aar.getGoon() ) break;
    		} 			
    		}
    		temporaryStr = "\"++++++++++++++++++ Plan Loaded ++++++++++++++++++\"";
    		println( temporaryStr );  
    		temporaryStr = "\" \"";
    		println( temporaryStr );  
    		temporaryStr = "\" \"";
    		println( temporaryStr );  
    		if( (guardVars = QActorUtils.evalTheGuard(this, " !?planName(PLANNAME)" )) != null ){
    		parg = "showPlan(path)";
    		parg = QActorUtils.substituteVars(guardVars,parg);
    		//REGENERATE AKKA
    		aar = solveGoalReactive(parg,1000,"","");
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "startNavigation";
    			if( ! aar.getGoon() ) break;
    		} 			
    		}
    		temporaryStr = "\" \"";
    		println( temporaryStr );  
    		temporaryStr = "\" \"";
    		println( temporaryStr );  
    		temporaryStr = "\"++++++++++++++++++ ++++++++++++++++++ ++++++++++++++++++\"";
    		println( temporaryStr );  
    		parg = "runResumablePlan(path)";
    		//REGENERATE AKKA
    		aar = solveGoalReactive(parg,2100000000,"","");
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "startNavigation";
    			if( ! aar.getGoon() ) break;
    		} 			
    break;
    }//while
    return returnValue;
    }catch(Exception e){
       //println( getName() + " plan=startNavigation WARNING:" + e.getMessage() );
       QActorContext.terminateQActorSystem(this); 
       return false;  
    }
    }
    public boolean abort() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "abort";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		temporaryStr = "\"Current command aborted\"";
    		println( temporaryStr );  
    		if( ! planUtils.switchToPlan("waitConsoleCommand").getGoon() ) break;
    break;
    }//while
    return returnValue;
    }catch(Exception e){
       //println( getName() + " plan=abort WARNING:" + e.getMessage() );
       QActorContext.terminateQActorSystem(this); 
       return false;  
    }
    }
    public boolean waitAndEvaluate() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "waitAndEvaluate";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		temporaryStr = "\"maybe there is an unexpected static obstacle\"";
    		println( temporaryStr );  
    		//delay
    		aar = delayReactive(60000,"" , "");
    		if( aar.getInterrupted() ) curPlanInExec   = "waitAndEvaluate";
    		if( ! aar.getGoon() ) break;
    		temporaryStr = "\"are you there obstacle ??\"";
    		println( temporaryStr );  
    		//senseEvent
    		timeoutval = 5000;
    		aar = planUtils.senseEvents( timeoutval,"obstacle","notifyUnexpectedObstacle",
    		"" , "",ActionExecMode.synch );
    		if( ! aar.getGoon() || aar.getTimeRemained() <= 0 ){
    			//println("			WARNING: sense timeout");
    			addRule("tout(senseevent,"+getName()+")");
    			//break;
    		}
    		returnValue = continueWork;  
    break;
    }//while
    return returnValue;
    }catch(Exception e){
       //println( getName() + " plan=waitAndEvaluate WARNING:" + e.getMessage() );
       QActorContext.terminateQActorSystem(this); 
       return false;  
    }
    }
    public boolean notifyUnexpectedObstacle() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "notifyUnexpectedObstacle";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		temporaryStr = "\"I found an unexpected static obstacle\"";
    		println( temporaryStr );  
    		parg = "getCurrentPosition(CURRENT)";
    		//REGENERATE AKKA
    		aar = solveGoalReactive(parg,2100000000,"","");
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "notifyUnexpectedObstacle";
    			if( ! aar.getGoon() ) break;
    		} 			
    		parg = "getObstaclePosition(OBJECT)";
    		//REGENERATE AKKA
    		aar = solveGoalReactive(parg,2100000000,"","");
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "notifyUnexpectedObstacle";
    			if( ! aar.getGoon() ) break;
    		} 			
    		temporaryStr = QActorUtils.unifyMsgContent(pengine, "update(OBJECT,CURRENT)","update(OBJECT,CURRENT)", guardVars ).toString();
    		emit( "update", temporaryStr );
    		temporaryStr = "\"Unexpected Obstacle notified, I wait the new plan\"";
    		println( temporaryStr );  
    		if( ! planUtils.switchToPlan("waitConsoleCommand").getGoon() ) break;
    break;
    }//while
    return returnValue;
    }catch(Exception e){
       //println( getName() + " plan=notifyUnexpectedObstacle WARNING:" + e.getMessage() );
       QActorContext.terminateQActorSystem(this); 
       return false;  
    }
    }
    public boolean notifyEndOfNavigation() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "notifyEndOfNavigation";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		temporaryStr = "\"� passato al piano successivo\"";
    		println( temporaryStr );  
    		parg = "notifyEnd";
    		//REGENERATE AKKA
    		aar = solveGoalReactive(parg,10000,"","");
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "notifyEndOfNavigation";
    			if( ! aar.getGoon() ) break;
    		} 			
    		temporaryStr = "\"ma la chiamata prolog fallisce per un motivo non ben definito\"";
    		println( temporaryStr );  
    break;
    }//while
    return returnValue;
    }catch(Exception e){
       //println( getName() + " plan=notifyEndOfNavigation WARNING:" + e.getMessage() );
       QActorContext.terminateQActorSystem(this); 
       return false;  
    }
    }
    public boolean handleTimeout() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "handleTimeout";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		temporaryStr = "\"timeout!! GOODBYE\"";
    		println( temporaryStr );  
    break;
    }//while
    return returnValue;
    }catch(Exception e){
       //println( getName() + " plan=handleTimeout WARNING:" + e.getMessage() );
       QActorContext.terminateQActorSystem(this); 
       return false;  
    }
    }
    public boolean explorationFailure() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "explorationFailure";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		temporaryStr = "\"Explore FAILURE\"";
    		println( temporaryStr );  
    break;
    }//while
    return returnValue;
    }catch(Exception e){
       //println( getName() + " plan=explorationFailure WARNING:" + e.getMessage() );
       QActorContext.terminateQActorSystem(this); 
       return false;  
    }
    }
    public boolean loadMapFailure() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "loadMapFailure";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		temporaryStr = "\"Load Map FAILURE\"";
    		println( temporaryStr );  
    break;
    }//while
    return returnValue;
    }catch(Exception e){
       //println( getName() + " plan=loadMapFailure WARNING:" + e.getMessage() );
       QActorContext.terminateQActorSystem(this); 
       return false;  
    }
    }
    public boolean findpathFailure() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "findpathFailure";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		temporaryStr = "\"Find Path FAILURE\"";
    		println( temporaryStr );  
    break;
    }//while
    return returnValue;
    }catch(Exception e){
       //println( getName() + " plan=findpathFailure WARNING:" + e.getMessage() );
       QActorContext.terminateQActorSystem(this); 
       return false;  
    }
    }
    public boolean navigationFailure() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "navigationFailure";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		temporaryStr = "\"Navigation FAILURE\"";
    		println( temporaryStr );  
    break;
    }//while
    return returnValue;
    }catch(Exception e){
       //println( getName() + " plan=navigationFailure WARNING:" + e.getMessage() );
       QActorContext.terminateQActorSystem(this); 
       return false;  
    }
    }
    public boolean alternativeFindpathFailure() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "alternativeFindpathFailure";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		temporaryStr = "\"Alternative Find Path FAILURE\"";
    		println( temporaryStr );  
    break;
    }//while
    return returnValue;
    }catch(Exception e){
       //println( getName() + " plan=alternativeFindpathFailure WARNING:" + e.getMessage() );
       QActorContext.terminateQActorSystem(this); 
       return false;  
    }
    }
    public boolean consultPrologFailure() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "consultPrologFailure";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		temporaryStr = "\"The consult is gone wrong, maybe there are errors in the prolog file\"";
    		println( temporaryStr );  
    break;
    }//while
    return returnValue;
    }catch(Exception e){
       //println( getName() + " plan=consultPrologFailure WARNING:" + e.getMessage() );
       QActorContext.terminateQActorSystem(this); 
       return false;  
    }
    }
    public boolean generalPrologFailure() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "generalPrologFailure";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		temporaryStr = "\"Prolog goal FAILURE\"";
    		println( temporaryStr );  
    break;
    }//while
    return returnValue;
    }catch(Exception e){
       //println( getName() + " plan=generalPrologFailure WARNING:" + e.getMessage() );
       QActorContext.terminateQActorSystem(this); 
       return false;  
    }
    }
    /* 
    * ------------------------------------------------------------
    * SENSORS
    * ------------------------------------------------------------
    */
    protected void initSensorSystem(){		
    	try {
    		String goal = "consult( \"./src/it/unibo/robot/sensorTheory.pl\" )";
    		SolveInfo sol = QActorUtils.solveGoal( goal ,pengine );
    		if( ! sol.isSuccess() ){
    			//println( "avatar initSensorSystem attempt to load sensorTheory "  );
    			goal = "consult( \"./sensorTheory.pl\" )";
    			QActorUtils.solveGoal( pengine, goal  );
    			//println( "avatar initSensorSystem= "  +  aar.getResult() );
    		}
    		addSensorObservers();
    	} catch (Exception e) {
    		e.printStackTrace();
    	}
    }
    /*
    //COMPONENTS
     RobotComponent motorleft 
     RobotComponent motorright 
    sensor distFrontMock simulated debug=0   
    sensor distLeftMock simulated debug=0   
    Composed component motors
    */
    protected void addSensorObservers(){
    	for (ISensor<?> sensor : Configurator.getInstance().getSensors()) {
    		//println( "robot sensor= "  + sensor.getDefStringRep() );
    		//println( "robot sensor class= "  + sensor.getClass().getName() );
        	if( sensor instanceof DistanceSensor){
        		DistanceSensor sensorDistance  = (DistanceSensor) sensor;
        		ISensorObserver<IDistanceSensorData> obs = new SensorObserver<IDistanceSensorData>(this,outEnvView);
        //		println( "avatar add observer to  "  + sensorDistance.getDefStringRep() );
        		sensorDistance.addObserver(  obs  ) ;
        	}
        	if( sensor instanceof LineSensor){
        		LineSensor sensorLine = (LineSensor) sensor;
         		ISensorObserver<ILineSensorData> obs = new SensorObserver<ILineSensorData>(this,outEnvView);
        //		println( "avatar add observer to  "  + sensorLine.getDefStringRep() );
        		sensorLine.addObserver(  obs  ) ;
        	}
         	if( sensor instanceof MagnetometerSensor){
        		MagnetometerSensor sensorMagneto = (MagnetometerSensor) sensor;
         		ISensorObserver<IMagnetometerSensorData> obs = new SensorObserver<IMagnetometerSensorData>(this,outEnvView);
        //		println( "avatar add observer to  "  + sensorMagneto.getDefStringRep() );
        		sensorMagneto.addObserver(  obs  ) ;
        	}
    		if( sensor instanceof ImpactSensor){
    			ImpactSensor sensorImpact = (ImpactSensor) sensor;
    			ISensorObserver<IImpactSensorData> obs = new SensorObserver<IImpactSensorData>(this,outEnvView);
    	//		println( "avatar add observer to  "  + sensorMagneto.getDefStringRep() );
    			sensorImpact.addObserver(  obs  ) ;
    		}
    	}		
    }	
    
 
	/* 
	* ------------------------------------------------------------
	* APPLICATION ACTIONS
	* ------------------------------------------------------------
	*/
	/* 
	* ------------------------------------------------------------
	* QUEUE  
	* ------------------------------------------------------------
	*/
	    protected void getMsgFromInputQueue(){
//	    	println( " %%%% getMsgFromInputQueue" ); 
	    	QActorMessage msg = mysupport.getMsgFromQueue(); //blocking
//	    	println( " %%%% getMsgFromInputQueue continues with " + msg );
	    	this.currentMessage = msg;
	    }
  }

