/* Generated by AN DISI Unibo */ 
package it.unibo.robot;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.ActorTerminationMessage;
import it.unibo.qactors.QActorMessage;
import it.unibo.qactors.QActorUtils;
import it.unibo.contactEvent.interfaces.IEventItem;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.action.ActionReceiveTimed;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.qactors.action.IMsgQueue;
import it.unibo.qactors.akka.QActor;


//REGENERATE AKKA: QActor instead QActorPlanned
public abstract class AbstractRobot extends QActor { 
	protected AsynchActionResult aar = null;
	protected boolean actionResult = true;
	protected alice.tuprolog.SolveInfo sol;
	//protected IMsgQueue mysupport ;  //defined in QActor
	protected String planFilePath    = null;
	protected String terminationEvId = "default";
	protected String parg="";
	protected boolean bres=false;
	protected IActorAction  action;
	
			protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
				return outEnvView;
			}
	
	
		public AbstractRobot(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
			super(actorId, myCtx,  
			"./srcMore/it/unibo/robot/WorldTheory.pl",
			setTheEnv( outEnvView )  , "init");		
			this.planFilePath = "./srcMore/it/unibo/robot/plans.txt";
			//Plan interpretation is done in Prolog
			//if(planFilePath != null) planUtils.buildPlanTable(planFilePath);
	 	}
		@Override
		protected void doJob() throws Exception {
			String name  = getName().replace("_ctrl", "");
			mysupport = (IMsgQueue) QActorUtils.getQActor( name );
	 		initSensorSystem();
			boolean res = init();
			//println(getName() + " doJob " + res );
		} 
		/* 
		* ------------------------------------------------------------
		* PLANS
		* ------------------------------------------------------------
		*/
	    public boolean init() throws Exception{	//public to allow reflection
	    try{
	    	curPlanInExec =  "init";
	    	boolean returnValue = suspendWork;
	    while(true){
	    nPlanIter++;
	    		temporaryStr = "\"Exploration interactivity Test\"";
	    		println( temporaryStr );  
	    		//ReceiveMsg
	    		 		 aar = planUtils.receiveAMsg(mysupport,1000000000, "" , "" ); 	//could block
	    				if( aar.getInterrupted() ){
	    					curPlanInExec   = "playTheGame";
	    					if( ! aar.getGoon() ) break;
	    				} 			
	    				//if( ! aar.getGoon() ){
	    					//System.out.println("			WARNING: receiveMsg in " + getName() + " TOUT " + aar.getTimeRemained() + "/" +  1000000000);
	    					//addRule("tout(receive,"+getName()+")");
	    				//} 		 
	    				//println(getName() + " received " + aar.getResult() );
	    		printCurrentMessage(false);
	    		//onMsg
	    		if( currentMessage.msgId().equals("exploredebug") ){
	    			String parg = "";
	    			/* SwitchPlan */
	    			parg =  updateVars(  Term.createTerm("exploredebug(START,BOUNDS)"), Term.createTerm("exploredebug(START,BOUNDS)"), 
	    				    		  					Term.createTerm(currentMessage.msgContent()), parg);
	    				if( parg != null ){
	    					 if( ! planUtils.switchToPlan("simulateExploration").getGoon() ) break; 
	    				}//else println("guard  fails");  //parg is null when there is no guard (onEvent)
	    		}if( planUtils.repeatPlan(0).getGoon() ) continue;
	    break;
	    }//while
	    return returnValue;
	    }catch(Exception e){
	       //println( getName() + " plan=init WARNING:" + e.getMessage() );
	       QActorContext.terminateQActorSystem(this); 
	       return false;  
	    }
	    }
	    public boolean simulateExploration() throws Exception{	//public to allow reflection
	    try{
	    	curPlanInExec =  "simulateExploration";
	    	boolean returnValue = suspendWork;
	    while(true){
	    nPlanIter++;
	    		temporaryStr = "\"let's explore!!\"";
	    		println( temporaryStr );  
	    		//delay
	    		aar = delayReactive(1000,"" , "");
	    		if( aar.getInterrupted() ) curPlanInExec   = "simulateExploration";
	    		if( ! aar.getGoon() ) break;
	    		temporaryStr = QActorUtils.unifyMsgContent(pengine, "expdata(POS,STATE)","expdata(position(0,3),clear)", guardVars ).toString();
	    		emit( "expdata", temporaryStr );
	    		//delay
	    		aar = delayReactive(1000,"" , "");
	    		if( aar.getInterrupted() ) curPlanInExec   = "simulateExploration";
	    		if( ! aar.getGoon() ) break;
	    		temporaryStr = QActorUtils.unifyMsgContent(pengine, "expdata(POS,STATE)","expdata(position(0,2),clear)", guardVars ).toString();
	    		emit( "expdata", temporaryStr );
	    		//delay
	    		aar = delayReactive(1000,"" , "");
	    		if( aar.getInterrupted() ) curPlanInExec   = "simulateExploration";
	    		if( ! aar.getGoon() ) break;
	    		temporaryStr = QActorUtils.unifyMsgContent(pengine, "expdata(POS,STATE)","expdata(position(0,1),clear)", guardVars ).toString();
	    		emit( "expdata", temporaryStr );
	    		//delay
	    		aar = delayReactive(1000,"" , "");
	    		if( aar.getInterrupted() ) curPlanInExec   = "simulateExploration";
	    		if( ! aar.getGoon() ) break;
	    		temporaryStr = QActorUtils.unifyMsgContent(pengine, "expdata(POS,STATE)","expdata(position(0,0),object)", guardVars ).toString();
	    		emit( "expdata", temporaryStr );
	    		//delay
	    		aar = delayReactive(1000,"" , "");
	    		if( aar.getInterrupted() ) curPlanInExec   = "simulateExploration";
	    		if( ! aar.getGoon() ) break;
	    		temporaryStr = QActorUtils.unifyMsgContent(pengine, "expdata(POS,STATE)","expdata(position(1,1),clear)", guardVars ).toString();
	    		emit( "expdata", temporaryStr );
	    		//delay
	    		aar = delayReactive(1000,"" , "");
	    		if( aar.getInterrupted() ) curPlanInExec   = "simulateExploration";
	    		if( ! aar.getGoon() ) break;
	    		temporaryStr = QActorUtils.unifyMsgContent(pengine, "expdata(POS,STATE)","expdata(position(1,0),clear)", guardVars ).toString();
	    		emit( "expdata", temporaryStr );
	    		//delay
	    		aar = delayReactive(1000,"" , "");
	    		if( aar.getInterrupted() ) curPlanInExec   = "simulateExploration";
	    		if( ! aar.getGoon() ) break;
	    		temporaryStr = QActorUtils.unifyMsgContent(pengine, "expdata(POS,STATE)","expdata(position(2,0),clear)", guardVars ).toString();
	    		emit( "expdata", temporaryStr );
	    		//delay
	    		aar = delayReactive(1000,"" , "");
	    		if( aar.getInterrupted() ) curPlanInExec   = "simulateExploration";
	    		if( ! aar.getGoon() ) break;
	    		temporaryStr = QActorUtils.unifyMsgContent(pengine, "expdata(POS,STATE)","expdata(position(3,0),clear)", guardVars ).toString();
	    		emit( "expdata", temporaryStr );
	    		//delay
	    		aar = delayReactive(1000,"" , "");
	    		if( aar.getInterrupted() ) curPlanInExec   = "simulateExploration";
	    		if( ! aar.getGoon() ) break;
	    		temporaryStr = QActorUtils.unifyMsgContent(pengine, "expdata(POS,STATE)","expdata(position(3,1),clear)", guardVars ).toString();
	    		emit( "expdata", temporaryStr );
	    		//delay
	    		aar = delayReactive(1000,"" , "");
	    		if( aar.getInterrupted() ) curPlanInExec   = "simulateExploration";
	    		if( ! aar.getGoon() ) break;
	    		temporaryStr = QActorUtils.unifyMsgContent(pengine, "expdata(POS,STATE)","expdata(position(3,2),clear)", guardVars ).toString();
	    		emit( "expdata", temporaryStr );
	    		//delay
	    		aar = delayReactive(1000,"" , "");
	    		if( aar.getInterrupted() ) curPlanInExec   = "simulateExploration";
	    		if( ! aar.getGoon() ) break;
	    		temporaryStr = QActorUtils.unifyMsgContent(pengine, "expdata(POS,STATE)","expdata(position(3,3),object)", guardVars ).toString();
	    		emit( "expdata", temporaryStr );
	    		//delay
	    		aar = delayReactive(1000,"" , "");
	    		if( aar.getInterrupted() ) curPlanInExec   = "simulateExploration";
	    		if( ! aar.getGoon() ) break;
	    		temporaryStr = QActorUtils.unifyMsgContent(pengine, "expdata(POS,STATE)","expdata(position(2,2),object)", guardVars ).toString();
	    		emit( "expdata", temporaryStr );
	    		//delay
	    		aar = delayReactive(1000,"" , "");
	    		if( aar.getInterrupted() ) curPlanInExec   = "simulateExploration";
	    		if( ! aar.getGoon() ) break;
	    		temporaryStr = QActorUtils.unifyMsgContent(pengine, "expdata(POS,STATE)","expdata(position(2,1),object)", guardVars ).toString();
	    		emit( "expdata", temporaryStr );
	    		//delay
	    		aar = delayReactive(1000,"" , "");
	    		if( aar.getInterrupted() ) curPlanInExec   = "simulateExploration";
	    		if( ! aar.getGoon() ) break;
	    		temporaryStr = QActorUtils.unifyMsgContent(pengine, "expdata(POS,STATE)","expdata(position(1,2),clear)", guardVars ).toString();
	    		emit( "expdata", temporaryStr );
	    		//delay
	    		aar = delayReactive(1000,"" , "");
	    		if( aar.getInterrupted() ) curPlanInExec   = "simulateExploration";
	    		if( ! aar.getGoon() ) break;
	    		temporaryStr = QActorUtils.unifyMsgContent(pengine, "expdata(POS,STATE)","expdata(position(1,3),clear)", guardVars ).toString();
	    		emit( "expdata", temporaryStr );
	    		//delay
	    		aar = delayReactive(1000,"" , "");
	    		if( aar.getInterrupted() ) curPlanInExec   = "simulateExploration";
	    		if( ! aar.getGoon() ) break;
	    		temporaryStr = QActorUtils.unifyMsgContent(pengine, "expdata(POS,STATE)","expdata(position(2,3),clear)", guardVars ).toString();
	    		emit( "expdata", temporaryStr );
	    		//delay
	    		aar = delayReactive(1000,"" , "");
	    		if( aar.getInterrupted() ) curPlanInExec   = "simulateExploration";
	    		if( ! aar.getGoon() ) break;
	    		temporaryStr = QActorUtils.unifyMsgContent(pengine, "end","end", guardVars ).toString();
	    		emit( "end", temporaryStr );
	    		returnValue = continueWork; //we must restore nPlanIter and curPlanInExec of the 'interrupted' plan
	    break;
	    }//while
	    return returnValue;
	    }catch(Exception e){
	       //println( getName() + " plan=simulateExploration WARNING:" + e.getMessage() );
	       QActorContext.terminateQActorSystem(this); 
	       return false;  
	    }
	    }
	    protected void initSensorSystem(){
	    	//doing nothing in a QActor
	    }
	    
	 
		/* 
		* ------------------------------------------------------------
		* APPLICATION ACTIONS
		* ------------------------------------------------------------
		*/
		/* 
		* ------------------------------------------------------------
		* QUEUE  
		* ------------------------------------------------------------
		*/
		    protected void getMsgFromInputQueue(){
	//	    	println( " %%%% getMsgFromInputQueue" ); 
		    	QActorMessage msg = mysupport.getMsgFromQueue(); //blocking
	//	    	println( " %%%% getMsgFromInputQueue continues with " + msg );
		    	this.currentMessage = msg;
		    }
	  }
	
